services:
  - mysql:5.6

stages:
  - test

test:
  stage: test
  before_script:
    - pip install flake8 pycodestyle pep8-naming
    - python setup.py sdist
    - pip install "git+git://github.com/ola-t/django-rest-framework-json-api@develop#egg=djangorestframework-jsonapi"
    - SRCDIR=$(pwd) docker/run.sh install

    - flake8 --version
    - flake8 -v .
    - mkdir -p ~/.yamjam && cp travis/config.yaml ~/.yamjam/

  script:
    - python setup.py test
