sudo: required
language: python

services:
  - docker

install:
  - pip install flake8 pycodestyle pep8-naming
  - pip install docker-compose

before_script:
  - docker --version
  - docker-compose -v
  - flake8 --version
  - flake8 -v .

script:
  - docker-compose -f dc-test.yml up --build --abort-on-container-exit
  - exit $(docker inspect -f '{{.State.ExitCode}}' ebimetagenomicsapi_test_1)
  - docker-compose -f dc-deploy.yml up --build --abort-on-container-exit
