sudo: required
language: python

python:
  - "3.5"
  - "3.6"

env:
  - MYSQL_HOST=127.0.0.1

services:
  - docker

install:
    # Bug fix: https://github.com/django-json-api/django-rest-framework-json-api/pull/359
  - pip install "git+git://github.com/django-json-api/django-rest-framework-json-api@develop#egg=djangorestframework-jsonapi"
  - pip install -r requirements.txt
  - pip install flake8 pycodestyle pep8-naming

before_script:
  - docker --version
  # travis by default comes with MySQL 5.5
  - sudo service mysql stop
  - docker run --rm --name mysql -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -d mysql:5.6

  - flake8 --version
  - flake8 -v .

script:
  - ./travis.sh

after_script:
  - docker stop mysql
