sudo: required
language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'

services:
  - docker
  - mongodb

before_install:
  - pip install flake8 pycodestyle pep8-naming
  - python setup.py sdist

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - SRCDIR=$(pwd) docker/run.sh install

before_script:
  - docker --version
  # travis by default comes with MySQL 5.5
  - sudo service mysql stop
  - docker run --rm --name mysql -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -d mysql:5.6
  # optional redis
  # - docker run --rm --name redis -p 6379:6379 -d redis
  - flake8 --version
  - flake8 -v .
  - mkdir -p ~/.yamjam && cp travis/config.yaml ~/.yamjam/

script:
  - SRCDIR=$(pwd) docker/run.sh travis
after_script:
  - docker stop mysql #redis

notifications:
  slack:
    secure: eZRPOy6OuEaSL/UKNfbOLaRF0mtyO65L0D2hrdQGizq52GtoUglP2W+pAMtRrWUIYrhz6/ZpP8P46YL+KjRi05v6dncTtfC7ZSEK3ugRO2cZVZ5kh8/7Eo+PuFTyUfhpCIMpI6hmkJTqHDcxgFe1LfJ1FRpGgi7ksKEQ5tYYvComdUr6JGTDu9HlfV+MeUWxiPDwIQRt8gpR6ViO9Y2Q1nPrnM0Yh2ntMYnyK6DR9WYUkn+VWOfxqoXKIFUvYM2qnWszYDnVmwI+rlWATGLHyiZlFxbocaIR9zySQcVF1K4BCv5qJAVmK65hcy0ESq+E6uyIvn1xireb8R8iAZBzS/h8WDcJaEU6gndIk4IyrxdJLDFwUwyZbyEQyri8Qo8RbocVbPIg45iRfrNFNW5kn3epDi+2jRq6QqKMhbbya8g1OyJQHR74+WrvnrxVp86mHn1dqubls/TW2o7BQgbLEO2IfmSAkDt6p281a905dt8mD7+isHXT5HaV2UWbbKRBbVVDvmJEXOz0XaoKSoFbjjLkTcAbZKvJ52AeB28I8OHUvDg6W/ZWbUe+iLA2EMLD+NKgKmRQGQCBkGmGaq3oaVDoVEu6549i9cckm+9RmMo8Hdn945EcsRKyOinEF4mddqril2w8b1me5W5loiseObbnhXjEM3Zru1IeedMSf8w=
