language: python
python:
  - "3.5"
  - "3.6"

install:
  # Bug fix: https://github.com/django-json-api/django-rest-framework-json-api/pull/359
  - pip install "git+git://github.com/django-json-api/django-rest-framework-json-api@develop#egg=djangorestframework-jsonapi"
  - pip install -r requirements.txt
  - pip install flake8 pycodestyle pep8-naming

script:
  - flake8 --version
  - flake8 -v .
  - python setup.py test