sudo: required
language: python

python:
#  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

services:
  - docker
  - mongodb

before_install:
  - pip install flake8 pycodestyle pep8-naming
  - python setup.py sdist

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - SRCDIR=$(pwd) PYTHON_VERSION=$TRAVIS_PYTHON_VERSION docker/run.sh install

before_script:
  - docker --version
  # travis by default comes with MySQL 5.5
  - sudo service mysql stop
  - docker run --rm --name mysql -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -d mysql:5.6
  # optional redis
  # - docker run --rm --name redis -p 6379:6379 -d redis
  - flake8 --version
  - flake8 -v .
  - mkdir -p ~/.yamjam && cp travis/config.yaml ~/.yamjam/

script:
  - SRCDIR=$(pwd) docker/run.sh travis
after_script:
  - docker stop mysql #redis

notifications:
  slack:
    secure: D1lBmpLSuEeXIk/LYekDz+tzH9jxIGw+ocCI44Pwzxq8hLzQ9vSR6m4djogWLjmgw6eqxd+RVj9i/9+eccuHJ9CNTl+8Hy8p2i6ou/OjAR2gRry/wFOuSBJyX2Lc8/tA8kuYstkXgCE7RpoI40gH/ksI2yr/rUKLLd9yUPpo3kdZ3ZZ2qpiaz38n8Hojp3BDjjzWc1cQfGat59uF5Pkf3PPjv2fHQglBSph1ei2ldY77ui71BBDTetXFOPchRo2Xl0mDCu3BVtro8xpXhAWgfFCtuwqSqXYrOhGXAI20Rkp+ZUrEGTIDmUNyMLVBO+V7S8o2D/K4XtMQbrAnpo2y4fQRiuFHtl+5wS6oj6S8ICl/CfKDyENzEGDZjB6jQ0ygix/z4rmdYjPcc9T+zBE8FJnC3SBzTEEFvMPZOm/nGYOOIFhr8jdvS78jXemTndhvWiDYtRY9guL4vseF8Cg/msOsaKbr9ZmPomk0mqZZ6eNv+4lUJvpczo7DiAQIoMEg0yLT/51raEzQd0JdrrTg8ePvH+vfYEgzxTv+TuCJ8S/kbxkh4zRDfqTUT3gIH5Y7+onpMiOHkZYufbso00JHyJM+LzocjxC5pzJ7TJteMt7RrLll4qf2+DQQ0p+kSnxf/LZklGFY4xVnI52fDPQHqWWwj1GfN/eojHoviuMCnqo=
