version: '2'
services: 

  mysql:
    image: mysql:5.6
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=emg

  test:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - .:/home/centos/src
    links:
      - mysql
    environment:
      - PYTHONUNBUFFERED=0
    entrypoint: /tmp/docker/run_test.sh
