version: '2'
services: 

  mysql:
    image: mysql:5.6
    volumes:
    #   - ./mysql:/var/lib/mysql:rw
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=emg

  emgapi_test:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - .:/home/centos/src
    links:
      - mysql
    environment:
      - PYTHONUNBUFFERED=0
    entrypoint: /tmp/docker/run_test.sh

  emgapi:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - .:/home/centos/src
    links:
      - mysql
    environment:
      - PYTHONUNBUFFERED=0

  nginx:
    image: nginx:1.10
    links:
      - emgapi
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
