emg:
  databases:
    # default:
    #   ENGINE: 'django.db.backends.mysql'
    #   NAME: 'emg'
    #   USER: 'root'
    #   PASSWORD: ''
    #   HOST: 0.0.0.0 # localhost won't work with docker
    #   PORT: 3306
  databases:
    default:
      ENGINE: 'django.db.backends.mysql'
      NAME: emg
      USER: emguser
      PASSWORD: emguser
      HOST: mysql-vm-076.ebi.ac.uk
      PORT: 4499
  
  # Is this used?
  # session_engine: 'django.contrib.sessions.backends.cache'
  # caches:
  #   default:
  #     BACKEND: "django_redis.cache.RedisCache"
  #     LOCATION: "redis://redis:6379/0"
  #     KEY_PREFIX: "emg"

  debug: true
  allowed_host: '*'
  prefix: '/metagenomics/api'
  results_dir: '/home/mbc/projects/emgapi/results/'

  secure_cookies: false

  emg_backend_auth:
    - 'emgapi.backends.EMGBackend'
    - 'django.contrib.auth.backends.ModelBackend'

  # mongodb:
  #   db: 'emgapi'
  #   host: 'localhost'

  mongodb:
    db: 'emgapi'
    host: 'mongodb://mongos-hxvm7-dev-001.ebi.ac.uk/emgapi?authSource=admin'
    username: 'emgapi'
    password: 'OfdduXhyGzu1'

  documentation:
    title: 'EBI Metagenomics API'
    description:
      >
        Is a free resource to visualise and discover metagenomic datasets.
        For more details go to http://www.ebi.ac.uk/metagenomics/'
