version: '2'
services: 

  mysql:
    image: mysql:5.6
    volumes:
      # - ./mysql:/var/lib/mysql:rw
      - ../schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=emg

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/home/emg/src
      - ../docker/config.yaml:/home/emg/emg/config.yaml:ro
    links:
      - mysql
      - mongodb
    environment:
      - PYTHONUNBUFFERED=0

  nginx:
    image: nginx:1.12
    links:
      - app
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
      - ../results:/results:ro
    ports:
      - "80:80"

  mongodb:
    image: mongo:3.4
