# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0003_annotations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='url',
            new_name='pub_url',
        ),
        migrations.AlterModelOptions(
            name='pipelinetool',
            options={'ordering': ('tool_name',)},
        ),

        migrations.CreateModel(
            name='AnalysisJobAnn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(db_column='JOB_ID', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_metadata', serialize=False, to='emgapi.AnalysisJob')),
                ('units', models.CharField(blank=True, db_column='UNITS', max_length=25, null=True)),
                ('var', models.ForeignKey(db_column='VAR_ID', on_delete=django.db.models.deletion.CASCADE, to='emgapi.VariableNames')),
                ('var_val_ucv', models.CharField(blank=True, db_column='VAR_VAL_UCV', max_length=4000, null=True)),
            ],
            options={
                'db_table': 'ANALYSIS_JOB_ANN',
            },
        ),
        migrations.AlterUniqueTogether(
            name='analysisjobann',
            unique_together=set([('job', 'var')]),
        ),

        migrations.RunSQL(
            # Production FOREIGN KEY may be different
            # """
            # ALTER TABLE GSC_CV_CV
            #     DROP FOREIGN KEY GSC_CV_CV_ibfk_1,
            #     MODIFY VAR_NAME VARCHAR(255);
            # """
            """
            LOCK TABLES
                GSC_CV_CV WRITE,
                VARIABLE_NAMES WRITE;

            ALTER TABLE GSC_CV_CV
                DROP FOREIGN KEY GSC_CV_CV_VAR_NAME_7b3b67e1_fk_VARIABLE_NAMES_VAR_ID,
                MODIFY VAR_NAME VARCHAR(255);

            ALTER TABLE VARIABLE_NAMES
                MODIFY VAR_NAME VARCHAR(255);

            ALTER TABLE GSC_CV_CV
                ADD CONSTRAINT GSC_CV_CV_VAR_NAME_7b3b67e1_fk_VARIABLE_NAMES_VAR_ID FOREIGN KEY (VAR_NAME)
                      REFERENCES VARIABLE_NAMES (VAR_NAME);

            UNLOCK TABLES;
            """
        ),

    ]
