# Generated by Django 3.2.12 on 2022-10-25 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0003_auto_20221011_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomecatalogue',
            name='last_update',
            field=models.DateTimeField(db_column='LAST_UPDATE', default=django.utils.timezone.now),
        ),
    ]
