# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0003_annotations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='url',
            new_name='pub_url',
        ),
        migrations.AlterModelOptions(
            name='pipelinetool',
            options={'ordering': ('tool_name',)},
        ),
        migrations.CreateModel(
            name='AnalysisMetadataVariableNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_name', models.CharField(db_column='VAR_NAME', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=255, null=True)),
            ],
            options={
                'db_table': 'SUMMARY_VARIABLE_NAMES',
            },
        ),
        migrations.AlterUniqueTogether(
            name='analysismetadatavariablenames',
            unique_together=set([('var_name', 'description')]),
        ),
        migrations.CreateModel(
            name='AnalysisJobAnn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(blank=True, db_column='UNITS', max_length=25, null=True)),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emgapi.AnalysisMetadataVariableNames')),
                ('var_val_ucv', models.CharField(blank=True, db_column='VAR_VAL_UCV', max_length=4000, null=True)),
                ('job', models.ForeignKey(db_column='JOB_ID', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_metadata', to='emgapi.AnalysisJob')),
            ],
            options={
                'db_table': 'ANALYSIS_JOB_ANN',
            },
        ),
        migrations.AlterUniqueTogether(
            name='analysisjobann',
            unique_together=set([('job', 'var')]),
        ),
    ]
