# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0004_analysisjobann'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='accession',
            field=models.CharField(db_column='EXT_SAMPLE_ID', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='primary_accession',
            field=models.CharField(db_column='PRIMARY_ACCESSION', max_length=20),
        ),

        migrations.AddField(
            model_name='analysisjob',
            name='secondary_accession',
            field=models.CharField(db_column='SECONDARY_ACCESSION', max_length=100),
        ),
        migrations.RunSQL(
            "UPDATE ANALYSIS_JOB as AJ "
            "SET AJ.SECONDARY_ACCESSION=AJ.EXTERNAL_RUN_IDS "
        ),

        migrations.AlterField(
            model_name='analysisjob',
            name='sample',
            field=models.ForeignKey(db_column='SAMPLE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='emgapi.Sample'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='study',
            field=models.ForeignKey(db_column='STUDY_ID', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='emgapi.Study'),
        ),
        migrations.RunSQL(
            "UPDATE ANALYSIS_JOB as AJ "
            "JOIN SAMPLE as SM ON (AJ.SAMPLE_ID=SM.SAMPLE_ID) "
            "SET AJ.STUDY_ID=SM.STUDY_ID "
        ),

        migrations.CreateModel(
            name='StudySample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.ForeignKey(db_column='STUDY_ID', on_delete=django.db.models.deletion.CASCADE, to='emgapi.Study', related_name='study_sample_set')),
                ('sample', models.ForeignKey(db_column='SAMPLE_ID', on_delete=django.db.models.deletion.CASCADE, to='emgapi.Sample', related_name='study_sample_set')),
            ],
            options={
                'db_table': 'STUDY_SAMPLE',
            },
        ),
        migrations.AlterUniqueTogether(
            name='studysample',
            unique_together=set([('study', 'sample')]),
        ),
        migrations.RunSQL(
            "INSERT INTO STUDY_SAMPLE (STUDY_ID, SAMPLE_ID) "
            "SELECT STUDY_ID, SAMPLE_ID from SAMPLE where SAMPLE_ID>0"
        ),
        migrations.RemoveField(
            model_name='sample',
            name='study',
        ),

    ]
