# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0005_study_sample_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySample',
            fields=[
                ('study', models.ForeignKey(db_column='STUDY_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emgapi.Study')),
                ('sample', models.ForeignKey(db_column='SAMPLE_ID', on_delete=django.db.models.deletion.CASCADE, to='emgapi.Sample')),
            ],
            options={
                'db_table': 'STUDY_SAMPLE',
            },
        ),
        migrations.RunSQL(
            "INSERT INTO STUDY_SAMPLE (study_id, sample_id) "
            "SELECT study_id, sample_id from SAMPLE where sample_id>0;"
        ),
        migrations.RemoveField(
            model_name='sample',
            name='study',
        ),
    ]
