# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0005_study_sample_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinereleasetool',
            name='pipeline',
            field=models.OneToOneField(db_column='PIPELINE_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emgapi.Pipeline'),
        ),
        migrations.AlterField(
            model_name='sampleann',
            name='sample',
            field=models.OneToOneField(db_column='SAMPLE_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='emgapi.Sample'),
        ),
        migrations.AlterField(
            model_name='samplepublication',
            name='sample',
            field=models.OneToOneField(db_column='SAMPLE_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emgapi.Sample'),
        ),
        migrations.AlterField(
            model_name='studypublication',
            name='study',
            field=models.OneToOneField(db_column='STUDY_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emgapi.Study'),
        ),
    ]
