# Generated by Django 3.2.12 on 2022-11-23 15:04

from django.db import migrations


def create_virify_genome_download_descriptions(apps, schema_editor):
    DownloadDescriptionLabel = apps.get_model("emgapi", "DownloadDescriptionLabel")
    DownloadDescriptionLabel.objects.create(
        description="Genome GFF file with VIRify viral annotations",
        description_label="Genome VIRify Annotation"
    )
    DownloadDescriptionLabel.objects.create(
        description="Genome TSV file with VIRify viral regions",
        description_label="Genome VIRify Regions"
    )


def remove_virify_genome_download_descriptions(apps, schema_editor):
    DownloadDescriptionLabel = apps.get_model("emgapi", "DownloadDescriptionLabel")
    DownloadDescriptionLabel.objects.filter(description_label="Genome VIRify Annotation").delete()
    DownloadDescriptionLabel.objects.filter(description_label="Genome VIRify Regions").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0005_auto_20221031_1531'),
    ]

    operations = [
        migrations.RunPython(
            code=create_virify_genome_download_descriptions,
            reverse_code=remove_virify_genome_download_descriptions,
        ),
    ]
