# Generated by Django 3.2.12 on 2022-11-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0006_auto_20221123_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superstudy',
            name='description',
            field=models.TextField(blank=True, db_column='DESCRIPTION', help_text='Use <a href="https://commonmark.org/help/" target="_newtab">markdown</a> for links and rich text.', null=True),
        ),
        migrations.CreateModel(
            name='SuperStudyGenomeCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_catalogue', models.ForeignKey(db_column='GENOME_CATALOGUE_ID', on_delete=django.db.models.deletion.CASCADE, to='emgapi.genomecatalogue')),
                ('super_study', models.ForeignKey(db_column='SUPER_STUDY_ID', on_delete=django.db.models.deletion.CASCADE, to='emgapi.superstudy')),
            ],
            options={
                'verbose_name_plural': 'super studies genome catalogues',
                'db_table': 'SUPER_STUDY_GENOME_CATALOGUE',
                'unique_together': {('genome_catalogue', 'super_study')},
            },
        ),
        migrations.AddField(
            model_name='superstudy',
            name='genome_catalogues',
            field=models.ManyToManyField(blank=True, related_name='super_studies', through='emgapi.SuperStudyGenomeCatalogue', to='emgapi.GenomeCatalogue'),
        ),
    ]
