# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0006_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadDataType',
            fields=[
                ('data_type_id', models.AutoField(db_column='DATA_TYPE_ID', primary_key=True, serialize=False)),
                ('data_type', models.CharField(db_column='DATA_TYPE', max_length=100)),
            ],
            options={
                'db_table': 'DOWNLOAD_DATA_TYPE',
            },
        ),
        migrations.AddField(
            model_name='analysisjobdownload',
            name='data_type',
            field=models.ForeignKey(blank=True, db_column='DATA_TYPE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.DownloadDataType'),
        ),
        migrations.AddField(
            model_name='studydownload',
            name='data_type',
            field=models.ForeignKey(blank=True, db_column='DATA_TYPE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.DownloadDataType'),
        ),
    ]
