# Generated by Django 3.2.12 on 2022-11-23 15:04

from django.db import migrations


def create_sanntis_genome_download_description(apps, schema_editor):
    DownloadDescriptionLabel = apps.get_model("emgapi", "DownloadDescriptionLabel")
    DownloadDescriptionLabel.objects.create(
        description="Genome GFF file with SanntiS SMBGC annotations",
        description_label="Genome SanntiS Annotation"
    )


def remove_sanntis_genome_download_description(apps, schema_editor):
    DownloadDescriptionLabel = apps.get_model("emgapi", "DownloadDescriptionLabel")
    DownloadDescriptionLabel.objects.filter(description_label="Genome SanntiS Annotation").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0006_auto_20221123_1504'),
    ]

    operations = [
        migrations.RunPython(
            code=create_sanntis_genome_download_description,
            reverse_code=remove_sanntis_genome_download_description,
        ),
    ]
