# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-24 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0006_download'),
    ]

    operations = [

        migrations.AlterField(
            model_name='experimenttype',
            name='experiment_type_id',
            field=models.SmallIntegerField(db_column='EXPERIMENT_TYPE_ID', primary_key=True, serialize=False),
        ),

        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(blank=True, db_column='EXTERNAL_RUN_IDS', max_length=100, null=True)),
                ('secondary_accession', models.CharField(blank=True, db_column='SECONDARY_ACCESSION', max_length=100, null=True)),
                ('run_status_id', models.IntegerField(blank=True, db_column='RUN_STATUS_ID', null=True)),
                ('sample', models.ForeignKey(blank=True, db_column='SAMPLE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='emgapi.Sample')),
                ('study', models.ForeignKey(blank=True, db_column='STUDY_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='emgapi.Study')),
                ('experiment_type', models.ForeignKey(blank=True, db_column='EXPERIMENT_TYPE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='emgapi.ExperimentType')),
                ('instrument_platform', models.CharField(blank=True, db_column='INSTRUMENT_PLATFORM', max_length=50, null=True)),
                ('instrument_model', models.CharField(blank=True, db_column='INSTRUMENT_MODEL', max_length=50, null=True)),
            ],
            options={
                'db_table': 'RUN',
            },
        ),

        migrations.AlterModelOptions(
            name='analysisjobdownload',
            options={'ordering': ('pipeline', 'group_type', 'alias')},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ('accession',)},
        ),
        migrations.AlterModelOptions(
            name='studydownload',
            options={'ordering': ('pipeline', 'group_type', 'alias')},
        ),

        migrations.RunSQL(
            """INSERT INTO RUN (EXTERNAL_RUN_IDS, SECONDARY_ACCESSION,
                RUN_STATUS_ID, SAMPLE_ID, STUDY_ID, EXPERIMENT_TYPE_ID,
                INSTRUMENT_PLATFORM, INSTRUMENT_MODEL)
            SELECT EXTERNAL_RUN_IDS, SECONDARY_ACCESSION,
                RUN_STATUS_ID, SAMPLE_ID, STUDY_ID, EXPERIMENT_TYPE_ID,
                INSTRUMENT_PLATFORM, INSTRUMENT_MODEL
            FROM ANALYSIS_JOB ORDER BY JOB_ID ASC"""
        )

    ]
