# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0007_split_run'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ('study_id',)},
        ),
        migrations.RenameField(
            model_name='study',
            old_name='accession',
            new_name='secondary_accession',
        ),
        migrations.AlterUniqueTogether(
            name='study',
            unique_together=set([('study_id', 'secondary_accession')]),
        ),
    ]
