# Generated by Django 3.2.12 on 2022-11-28 17:15
import logging

from django.db import migrations, models
import django.db.models.deletion


def migrate_biome_related_superstudystudies_to_manually_curated_list(apps, schema_editor):
    SuperStudy = apps.get_model("emgapi", "SuperStudy")
    SuperStudyStudy = apps.get_model("emgapi", "SuperStudyStudy")
    for super_study in SuperStudy.objects.all():
        for biome in super_study.biomes.all():
            logging.info(f'Migrating studies from biome {biome} in superstudy {super_study}')
            for study in biome.studies.filter(
                    is_suppressed=False,
                    is_private=False
            ):
                SuperStudyStudy.objects.create(
                    super_study=super_study,
                    study=study,
                    is_flagship=False
                )
                logging.info(f'Study {study} added to superstudy {super_study}')


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0007_sanntis_genome_download'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superstudy',
            old_name='flagship_studies',
            new_name='studies',
        ),
        migrations.AddField(
            model_name='superstudystudy',
            name='is_flagship',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='superstudy',
            name='description',
            field=models.TextField(blank=True, db_column='DESCRIPTION', help_text='Use <a href="https://commonmark.org/help/" target="_newtab">markdown</a> for links and rich text.', null=True),
        ),
        migrations.RunPython(
            code=migrate_biome_related_superstudystudies_to_manually_curated_list,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.CreateModel(
            name='SuperStudyGenomeCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_catalogue', models.ForeignKey(db_column='GENOME_CATALOGUE_ID', on_delete=django.db.models.deletion.CASCADE, to='emgapi.genomecatalogue')),
                ('super_study', models.ForeignKey(db_column='SUPER_STUDY_ID', on_delete=django.db.models.deletion.CASCADE, to='emgapi.superstudy')),
            ],
            options={
                'verbose_name_plural': 'super studies genome catalogues',
                'db_table': 'SUPER_STUDY_GENOME_CATALOGUE',
                'unique_together': {('genome_catalogue', 'super_study')},
            },
        ),
        migrations.AddField(
            model_name='superstudy',
            name='genome_catalogues',
            field=models.ManyToManyField(blank=True, related_name='super_studies', through='emgapi.SuperStudyGenomeCatalogue', to='emgapi.GenomeCatalogue'),
        ),
    ]
