# Generated by Django 3.2.18 on 2023-09-08 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0009_genome_annotations_v2_downloads'),
    ]

    operations = [
        migrations.CreateModel(
            name='ME_Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokerID', models.CharField(blank=True, db_column='BROKER', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetagenomicsExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_created', models.DateTimeField(auto_now_add=True, db_column='FIRST_CREATED')),
                ('last_update', models.DateTimeField(auto_now=True, db_column='LAST_UPDATE')),
                ('broker_id', models.ForeignKey(db_column='BROKER', on_delete=django.db.models.deletion.CASCADE, to='emgapi.me_broker')),
            ],
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='metagenomics_exchange',
            field=models.ForeignKey(blank=True, db_column='METAGENOMICS_EXCHANGE', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.metagenomicsexchange'),
        ),
    ]
