# Generated by Django 3.2.18 on 2023-09-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0010_runextraannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='analysis_summary_json',
            field=models.JSONField(blank=True, db_column='ANALYSIS_SUMMARY_JSON', null=True),
        ),
    ]
