# Generated by Django 3.2.18 on 2023-09-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0010_runextraannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='job_operator_2',
            field=models.CharField(blank=True, db_column='JOB_OPERATOR_2', max_length=15, null=True),
        ),
    ]
