# Generated by Django 3.2.18 on 2023-09-12 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0010_auto_20230908_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisjob',
            name='metagenomics_exchange',
        ),
        migrations.AddField(
            model_name='metagenomicsexchange',
            name='analysis_id',
            field=models.ForeignKey(blank=True, db_column='ANALYSIS_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.analysisjob'),
        ),
    ]
