# Generated by Django 3.2.18 on 2023-11-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0011_auto_20230912_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metagenomicsexchange',
            name='analysis_id',
        ),
        migrations.RemoveField(
            model_name='metagenomicsexchange',
            name='broker_id',
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='last_populated_me',
            field=models.DateTimeField(blank=True, db_column='LAST_POPULATED_ME', help_text='Date at which this model was last appeared in Metagenomics Exchange', null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='last_updated_me',
            field=models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_ME'),
        ),
        migrations.DeleteModel(
            name='ME_Broker',
        ),
        migrations.DeleteModel(
            name='MetagenomicsExchange',
        ),
    ]
