# Generated by Django 3.2.18 on 2023-10-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0011_analysisjob_analysis_summary_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='last_indexed',
            field=models.DateTimeField(blank=True, db_column='LAST_INDEXED', help_text='Date at which this model was last included in an EBI Search initial/incremental index.', null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='last_update',
            field=models.DateTimeField(auto_now=True, db_column='LAST_UPDATE'),
        ),
    ]
