# Generated by Django 3.2.18 on 2023-09-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0011_analysisjob_analysis_summary_json'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisJobAnn',
        ),
    ]
