# Generated by Django 3.2.18 on 2023-09-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0012_remove_analysisjob_job_operator_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='analysis_summary_two',
            field=models.JSONField(blank=True, db_column='ANALYSIS_SUMMARY_TWO', null=True),
        ),
    ]
