# Generated by Django 3.2.18 on 2024-01-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0012_alter_publication_pub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='last_ebi_search_indexed',
            field=models.DateTimeField(blank=True, db_column='LAST_EBI_SEARCH_INDEXED', help_text='Date at which this model was last included in an EBI Search initial/incremental index.', null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='last_mgx_indexed',
            field=models.DateTimeField(blank=True, db_column='LAST_MGX_INDEXED', help_text='Date at which this model was last indexed in the Metagenomics Exchange', null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='mgx_accession',
            field=models.CharField(blank=True, db_column='MGX_ACCESSION', help_text='The Metagenomics Exchange accession.', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='study',
            name='last_ebi_search_indexed',
            field=models.DateTimeField(blank=True, db_column='LAST_EBI_SEARCH_INDEXED', help_text='Date at which this model was last included in an EBI Search initial/incremental index.', null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='last_update',
            field=models.DateTimeField(auto_now=True, db_column='LAST_UPDATE'),
        ),
    ]
