# Generated by Django 3.2.18 on 2023-10-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0012_auto_20231020_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='last_indexed',
            field=models.DateTimeField(blank=True, db_column='LAST_INDEXED', help_text='Date at which this model was last included in an EBI Search initial/incremental index.', null=True),
        ),
    ]
