# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-07 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('emgapi', '0012_auto_20190507_1219'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analysisjob',
            unique_together=set([]),
        ),
    ]
