# Generated by Django 3.2.18 on 2023-10-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0013_study_last_indexed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='last_update',
            field=models.DateTimeField(auto_now=True, db_column='LAST_UPDATE'),
        ),
    ]
