# Generated by Django 3.2.18 on 2023-09-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0013_analysisjob_analysis_summary_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisjob',
            name='analysis_summary_two',
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='analysis_summary_json',
            field=models.JSONField(blank=True, db_column='ANALYSIS_SUMMARY_JSON', null=True),
        ),
    ]
