# Generated by Django 3.2.18 on 2024-01-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0013_auto_20240118_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='last_update',
            field=models.DateTimeField(auto_now=True, db_column='LAST_UPDATE'),
        ),
    ]
