# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0013_super_studies'),
        ('emgapi', '0014_study_publication_pk_fix'),
    ]

    operations = [
    ]
