# Generated by Django 3.2.23 on 2024-01-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0015_last_updates_on_ebi_searchable_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedstudy',
            options={'managed': False, 'verbose_name': 'blacklisted study', 'verbose_name_plural': 'blacklisted studies'},
        ),
        migrations.RenameField(
            model_name='analysisjob',
            old_name='analysis_summary_json',
            new_name='analysis_summary',
        ),
    ]
