# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0015_super_studies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superstudy',
            options={'verbose_name_plural': 'super studies'},
        ),
        migrations.AddField(
            model_name='superstudy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='super-studies-img'),
        ),
        migrations.AlterField(
            model_name='superstudy',
            name='description',
            field=models.TextField(blank=True, db_column='DESCRIPTION', null=True),
        ),
    ]
