# Generated by Django 3.2.23 on 2025-03-05 15:52

from django.db import migrations, models


def migrate_unlabelled_catalogues(apps, schema_editor):
    GenomeCatalogue = apps.get_model("emgapi", "GenomeCatalogue")

    for catalogue in GenomeCatalogue.objects.filter(catalogue_biome_label="TODO").all():
        slug = catalogue.catalogue_id  # e.g. a-very-big-cat-v2-1
        versionless_slug = "-v".join(slug.split("-v")[:-1])  # e.g. a-very-big-cat
        catalogue.catalogue_biome_label = versionless_slug.replace("-", " ").title()
        catalogue.save()


def unmigrate_catalogue_biome_labels(apps, schema_editor):
    GenomeCatalogue = apps.get_model("emgapi", "GenomeCatalogue")
    for catalogue in GenomeCatalogue.objects.all():
        catalogue.catalogue_biome_label = "TODO"
        catalogue.save()


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0018_genome_annotations_v2_4_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomecatalogue',
            name='catalogue_biome_label',
            field=models.CharField(db_column='CATALOGUE_BIOME_LABEL', default='TODO', help_text='The biome label for the catalogue (and any others that share the same practical biome). Need not be a GOLD biome, e.g. may include host species.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genomecatalogue',
            name='catalogue_type',
            field=models.CharField(choices=[('prokaryotes', 'prokaryotes'), ('eukaryotes', 'eukaryotes'), ('viruses', 'viruses')], db_column='CATALOGUE_TYPE', default='prokaryotes', max_length=20),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=migrate_unlabelled_catalogues,
            reverse_code=unmigrate_catalogue_biome_labels,
        ),
        migrations.AlterField(
            model_name='genomecatalogue',
            name='catalogue_biome_label',
            field=models.CharField(db_column='CATALOGUE_BIOME_LABEL', help_text='The biome label for the catalogue (and any others that share the same practical biome). Need not be a GOLD biome, e.g. may include host species.', max_length=100),
        ),
        migrations.AlterField(
            model_name='genomecatalogue',
            name='catalogue_type',
            field=models.CharField(choices=[('prokaryotes', 'prokaryotes'), ('eukaryotes', 'eukaryotes'), ('viruses', 'viruses')], db_column='CATALOGUE_TYPE', max_length=20),
        )
    ]
