# Generated by Django 3.2.23 on 2025-03-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0019_auto_20250305_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='busco_completeness',
            field=models.FloatField(blank=True, db_column='BUSCO_COMPLETENESS', null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='rna_18s',
            field=models.FloatField(blank=True, db_column='RNA_18S', null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='rna_28s',
            field=models.FloatField(blank=True, db_column='RNA_28S', null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='rna_5_8s',
            field=models.FloatField(blank=True, db_column='RNA_5_8S', null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='rna_16s',
            field=models.FloatField(blank=True, db_column='RNA_16S', null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='rna_23s',
            field=models.FloatField(blank=True, db_column='RNA_23S', null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='rna_5s',
            field=models.FloatField(blank=True, db_column='RNA_5S', null=True),
        ),
    ]
