# Generated by Django 3.2.23 on 2025-03-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0020_auto_20250321_1242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genomecatalogue',
            unique_together={('catalogue_biome_label', 'version', 'catalogue_type')},
        ),
    ]
