# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-18 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

_new_descriptions = (
    ("Genome GFF file with antiSMASH geneclusters annotations", "Genome antiSMASH Annotation"),
    ("Tree generated from the pairwise Mash distances of conspecific genomes",
     "Pairwise Mash distances of conspecific genomes")
)


def add_download_descriptions(apps, schema_editor):
    db_name = schema_editor.connection.alias
    model = apps.get_model('emgapi', 'DownloadDescriptionLabel')
    for desc in _new_descriptions:
        model.objects.using(db_name).create(
            description=desc[0],
            description_label=desc[1])
    FileFormat = apps.get_model("emgapi", "FileFormat")
    ff = FileFormat(
        format_name="Newick format",
        format_extension="nwk",
        compression=0,
    )
    ff.save()


def remove_download_descriptions(apps, schema_editor):
    db_name = schema_editor.connection.alias
    model = apps.get_model('emgapi', 'DownloadDescriptionLabel')
    for desc in _new_descriptions:
        model.objects.using(db_name).filter(
            description=desc[0],
            description_label=desc[1]).delete()
    FileFormat = apps.get_model("emgapi", "FileFormat")
    try:
        ff = FileFormat.objects.get(
            format_name="Newick format",
            format_extension="nwk",
            compression=0,
        )
        ff.delete()
    except FileFormat.NotFound:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0020_auto_20200114_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiSmashGC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='NAME', max_length=80)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=80)),
            ],
            options={
                'db_table': 'ANTISMASH_GENECLUSTER',
            },
        ),
        migrations.CreateModel(
            name='GenomeAntiSmashGCCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_count', models.IntegerField(db_column='GENOME_COUNT')),
                ('antismash_genecluster', models.ForeignKey(db_column='ANTISMASH_GENECLUSTER', on_delete=django.db.models.deletion.DO_NOTHING, to='emgapi.AntiSmashGC')),
                ('genome', models.ForeignKey(db_column='GENOME_ID', on_delete=django.db.models.deletion.CASCADE, to='emgapi.Genome')),
            ],
            options={
                'db_table': 'GENOME_ANTISMASH_GENECLUSTER_COUNTS',
            },
        ),
        migrations.AddField(
            model_name='genome',
            name='antismash_geneclusters',
            field=models.ManyToManyField(through='emgapi.GenomeAntiSmashGCCounts', to='emgapi.AntiSmashGC'),
        ),
        migrations.AlterUniqueTogether(
            name='genomeantismashgccounts',
            unique_together=set([('genome', 'antismash_genecluster')]),
        ),
        migrations.RunPython(add_download_descriptions, reverse_code=remove_download_descriptions),
    ]
