# Generated by Django 3.2.23 on 2025-03-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0021_alter_genomecatalogue_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomecatalogue',
            name='other_stats',
            field=models.JSONField(blank=True, db_column='OTHER_STATS_JSON', null=True),
        ),
    ]
