# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-19 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0021_auto_20200218_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='cmseq',
            field=models.FloatField(db_column='CMSEQ', null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='taxincons',
            field=models.FloatField(db_column='TAXINCONS', default=0.0),
            preserve_default=False,
        ),
    ]
