# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-15 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0024_auto_20200505_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecksumAlgorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='NAME', max_length=255)),
            ],
            options={
                'db_table': 'CHECKSUM_ALGORITHM',
            },
        ),
        migrations.AddField(
            model_name='analysisjobdownload',
            name='file_checksum',
            field=models.CharField(blank=True, db_column='CHECKSUM', max_length=255),
        ),
        migrations.AddField(
            model_name='genomedownload',
            name='file_checksum',
            field=models.CharField(blank=True, db_column='CHECKSUM', max_length=255),
        ),
        migrations.AddField(
            model_name='releasedownload',
            name='file_checksum',
            field=models.CharField(blank=True, db_column='CHECKSUM', max_length=255),
        ),
        migrations.AddField(
            model_name='studydownload',
            name='file_checksum',
            field=models.CharField(blank=True, db_column='CHECKSUM', max_length=255),
        ),
        migrations.AddField(
            model_name='analysisjobdownload',
            name='checksum_algorithm',
            field=models.ForeignKey(blank=True, db_column='CHECKSUM_ALGORITHM', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.ChecksumAlgorithm'),
        ),
        migrations.AddField(
            model_name='genomedownload',
            name='checksum_algorithm',
            field=models.ForeignKey(blank=True, db_column='CHECKSUM_ALGORITHM', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.ChecksumAlgorithm'),
        ),
        migrations.AddField(
            model_name='releasedownload',
            name='checksum_algorithm',
            field=models.ForeignKey(blank=True, db_column='CHECKSUM_ALGORITHM', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.ChecksumAlgorithm'),
        ),
        migrations.AddField(
            model_name='studydownload',
            name='checksum_algorithm',
            field=models.ForeignKey(blank=True, db_column='CHECKSUM_ALGORITHM', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.ChecksumAlgorithm'),
        ),
    ]
