# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 11:02
from __future__ import unicode_literals

from django.db import migrations
from django.db import transaction


def rename_eggnog_description_labels(apps, schema_editor):
    DownloadDescriptionLabel = apps.get_model("emgapi", "DownloadDescriptionLabel")

    new_eggnog_description_labels = (
        ("EggNog annotation", "eggNOG annotation"),
        ("EggNog annotation (core and accessory)", "eggNOG annotation (core and accessory)"),
    )

    with transaction.atomic():
        for v in new_eggnog_description_labels:
            obj = DownloadDescriptionLabel.objects.get(
                description_label=v[0])
            obj.description_label = v[1]
            obj.save()


def create_download_description(apps, schema_editor):
    DownloadDescriptionLabel = apps.get_model("emgapi", "DownloadDescriptionLabel")
    downloads = (
        ("Combined (eggNOG, InterPro, antiSMASH) annotation", "Combined (eggNOG, InterPro, antiSMASH) annotation"),
        ("TSV formatted file containing eggNOG seed orthologs", "eggNOG seed orthologs"),
    )
    _downloads = list()
    for d in downloads:
        _downloads.append(
            DownloadDescriptionLabel(
                description=d[0],
                description_label=d[1]
            )
        )
    DownloadDescriptionLabel.objects.bulk_create(_downloads)


class Migration(migrations.Migration):
    dependencies = [
        ('emgapi', '0025_auto_20200605_1838'),
    ]

    operations = [
        migrations.RunPython(create_download_description),
        migrations.RunPython(rename_eggnog_description_labels),
    ]
