# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 11:02
from __future__ import unicode_literals

from django.db import migrations


def create_download_description(apps, schema_editor):
    DownloadDescriptionLabel = apps.get_model("emgapi", "DownloadDescriptionLabel")
    downloads = (
        ("Combined (eggNOG, InterPro, antiSMASH) annotation", "Combined (eggNOG, InterPro, antiSMASH) annotation"),
        ("TSV formatted file containing eggNOG seed orthologs", "eggNOG seed orthologs"),
    )
    _downloads = list()
    for d in downloads:
        _downloads.append(
            DownloadDescriptionLabel(
                description=d[0],
                description_label=d[1]
            )
        )
    DownloadDescriptionLabel.objects.bulk_create(_downloads)


class Migration(migrations.Migration):
    dependencies = [
        ('emgapi', '0025_auto_20200605_1838'),
    ]

    operations = [
        migrations.RunPython(create_download_description),
    ]
