# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-06 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0026_auto_20200612_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecksumAlgorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='NAME', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'CHECKSUM_ALGORITHM',
            },
        ),
        migrations.AlterModelOptions(
            name='analysismetadatavariablenames',
            options={'verbose_name': 'analysis meta variable name'},
        ),
        migrations.AlterModelOptions(
            name='antismashgc',
            options={'verbose_name_plural': 'antiSMASH clusters'},
        ),
        migrations.AlterModelOptions(
            name='assembly',
            options={'ordering': ('accession',), 'verbose_name_plural': 'assemblies'},
        ),
        migrations.AlterModelOptions(
            name='assemblyrun',
            options={'verbose_name_plural': 'assembly runs'},
        ),
        migrations.AlterModelOptions(
            name='assemblysample',
            options={'verbose_name_plural': 'assembly samples'},
        ),
        migrations.AlterModelOptions(
            name='blacklistedstudy',
            options={'managed': False, 'verbose_name_plural': 'blacklisted studies'},
        ),
        migrations.AlterModelOptions(
            name='cogcat',
            options={'verbose_name_plural': 'COG categories'},
        ),
        migrations.AlterModelOptions(
            name='variablenames',
            options={'verbose_name': 'variable name'},
        ),
        migrations.AddField(
            model_name='analysisjobdownload',
            name='file_checksum',
            field=models.CharField(blank=True, db_column='CHECKSUM', max_length=255),
        ),
        migrations.AddField(
            model_name='genomedownload',
            name='file_checksum',
            field=models.CharField(blank=True, db_column='CHECKSUM', max_length=255),
        ),
        migrations.AddField(
            model_name='releasedownload',
            name='file_checksum',
            field=models.CharField(blank=True, db_column='CHECKSUM', max_length=255),
        ),
        migrations.AddField(
            model_name='studydownload',
            name='file_checksum',
            field=models.CharField(blank=True, db_column='CHECKSUM', max_length=255),
        ),
        migrations.AlterField(
            model_name='genome',
            name='ena_genome_accession',
            field=models.CharField(blank=True, db_column='ENA_GENOME_ACCESSION', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='ena_sample_accession',
            field=models.CharField(blank=True, db_column='ENA_SAMPLE_ACCESSION', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='geo_origin',
            field=models.ForeignKey(blank=True, db_column='GEOGRAPHIC_ORIGIN', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.GeographicLocation'),
        ),
        migrations.AlterField(
            model_name='genome',
            name='img_genome_accession',
            field=models.CharField(blank=True, db_column='IMG_GENOME_ACCESSION', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='ncbi_genome_accession',
            field=models.CharField(blank=True, db_column='NCBI_GENOME_ACCESSION', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='ncbi_sample_accession',
            field=models.CharField(blank=True, db_column='NCBI_SAMPLE_ACCESSION', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='ncbi_study_accession',
            field=models.CharField(blank=True, db_column='NCBI_STUDY_ACCESSION', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='num_genomes_non_redundant',
            field=models.IntegerField(blank=True, db_column='PANGENOME_NON_RED_GENOMES', null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='num_genomes_total',
            field=models.IntegerField(blank=True, db_column='PANGENOME_TOTAL_GENOMES', null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='pangenome_accessory_size',
            field=models.IntegerField(blank=True, db_column='PANGENOME_ACCESSORY_PROP', null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='pangenome_core_size',
            field=models.IntegerField(blank=True, db_column='PANGENOME_CORE_PROP', null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='pangenome_eggnog_coverage',
            field=models.FloatField(blank=True, db_column='PANGENOME_EGGNOG_COV', null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='pangenome_ipr_coverage',
            field=models.FloatField(blank=True, db_column='PANGENOME_IPR_COV', null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='pangenome_size',
            field=models.IntegerField(blank=True, db_column='PANGENOME_SIZE', null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='patric_genome_accession',
            field=models.CharField(blank=True, db_column='PATRIC_GENOME_ACCESSION', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='analysisjobdownload',
            name='checksum_algorithm',
            field=models.ForeignKey(blank=True, db_column='CHECKSUM_ALGORITHM', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.ChecksumAlgorithm'),
        ),
        migrations.AddField(
            model_name='genomedownload',
            name='checksum_algorithm',
            field=models.ForeignKey(blank=True, db_column='CHECKSUM_ALGORITHM', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.ChecksumAlgorithm'),
        ),
        migrations.AddField(
            model_name='releasedownload',
            name='checksum_algorithm',
            field=models.ForeignKey(blank=True, db_column='CHECKSUM_ALGORITHM', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.ChecksumAlgorithm'),
        ),
        migrations.AddField(
            model_name='studydownload',
            name='checksum_algorithm',
            field=models.ForeignKey(blank=True, db_column='CHECKSUM_ALGORITHM', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.ChecksumAlgorithm'),
        ),
    ]
