# Generated by Django 3.2 on 2021-06-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0031_superstudy_url_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superstudy',
            name='image',
        ),
        migrations.AddField(
            model_name='superstudy',
            name='logo',
            field=models.CharField(blank=True, db_column='LOGO', max_length=100000, null=True),
        ),
    ]
