# Generated by Django 3.2.4 on 2021-07-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0032_auto_20210615_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeCatalogue',
            fields=[
                ('catalogue_id', models.SlugField(db_column='CATALOGUE_ID', max_length=100, primary_key=True, serialize=False)),
                ('version', models.CharField(db_column='VERSION', max_length=20)),
                ('name', models.CharField(db_column='NAME', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', help_text='Use <a href="https://commonmark.org/help/" target="_newtab">markdown</a> for links and rich text.', null=True)),
                ('protein_catalogue_name', models.CharField(blank=True, db_column='PROTEIN_CATALOGUE_NAME', max_length=100, null=True)),
                ('protein_catalogue_description', models.TextField(blank=True, db_column='PROTEIN_CATALOGUE_DESCRIPTION', help_text='Use <a href="https://commonmark.org/help/" target="_newtab">markdown</a> for links and rich text.', null=True)),
                ('last_update', models.DateTimeField(auto_now=True, db_column='LAST_UPDATE')),
                ('result_directory', models.CharField(db_column='RESULT_DIRECTORY', max_length=100)),
                ('biome', models.ForeignKey(db_column='BIOME_ID', on_delete=django.db.models.deletion.CASCADE, to='emgapi.biome')),
            ],
        ),
        migrations.CreateModel(
            name='GenomeCatalogueDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(db_column='REAL_NAME', max_length=255)),
                ('alias', models.CharField(db_column='ALIAS', max_length=255)),
                ('file_checksum', models.CharField(blank=True, db_column='CHECKSUM', max_length=255)),
                ('checksum_algorithm', models.ForeignKey(blank=True, db_column='CHECKSUM_ALGORITHM', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.checksumalgorithm')),
                ('description', models.ForeignKey(blank=True, db_column='DESCRIPTION_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.downloaddescriptionlabel')),
                ('file_format', models.ForeignKey(blank=True, db_column='FORMAT_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.fileformat')),
                ('genome_catalogue', models.ForeignKey(db_column='GENOME_CATALOGUE_ID', on_delete=django.db.models.deletion.CASCADE, to='emgapi.genomecatalogue')),
                ('group_type', models.ForeignKey(blank=True, db_column='GROUP_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.downloadgrouptype')),
                ('parent_id', models.ForeignKey(blank=True, db_column='PARENT_DOWNLOAD_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='emgapi.genomecataloguedownload')),
                ('subdir', models.ForeignKey(blank=True, db_column='SUBDIR_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='emgapi.downloadsubdir')),
            ],
            options={
                'db_table': 'GENOME_CATALOGUE_DOWNLOAD',
                'ordering': ('group_type', 'alias'),
                'unique_together': {('realname', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='GenomeCatalogueGenomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'GENOME_CATALOGUE_GENOMES',
            },
        ),
        migrations.CreateModel(
            name='GenomeCatalogueSeries',
            fields=[
                ('catalogue_series_id', models.SlugField(db_column='CATALOGUE_SERIES_ID', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=100, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='releasedownload',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='releasedownload',
            name='checksum_algorithm',
        ),
        migrations.RemoveField(
            model_name='releasedownload',
            name='description',
        ),
        migrations.RemoveField(
            model_name='releasedownload',
            name='file_format',
        ),
        migrations.RemoveField(
            model_name='releasedownload',
            name='group_type',
        ),
        migrations.RemoveField(
            model_name='releasedownload',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='releasedownload',
            name='release',
        ),
        migrations.RemoveField(
            model_name='releasedownload',
            name='subdir',
        ),
        migrations.AlterUniqueTogether(
            name='releasegenomes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='releasegenomes',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='releasegenomes',
            name='release',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='releases',
        ),
        migrations.DeleteModel(
            name='Release',
        ),
        migrations.DeleteModel(
            name='ReleaseDownload',
        ),
        migrations.DeleteModel(
            name='ReleaseGenomes',
        ),
        migrations.AddField(
            model_name='genomecataloguegenomes',
            name='genome',
            field=models.ForeignKey(db_column='GENOME_ID', on_delete=django.db.models.deletion.CASCADE, to='emgapi.genome'),
        ),
        migrations.AddField(
            model_name='genomecataloguegenomes',
            name='genome_catalogue',
            field=models.ForeignKey(db_column='CATALOGUE_ID', on_delete=django.db.models.deletion.CASCADE, to='emgapi.genomecatalogue'),
        ),
        migrations.AddField(
            model_name='genomecatalogue',
            name='catalogue_series',
            field=models.ForeignKey(db_column='GENOME_CATALOGUE_SERIES_ID', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='emgapi.genomecatalogueseries'),
        ),
        migrations.AddField(
            model_name='genome',
            name='catalogues',
            field=models.ManyToManyField(through='emgapi.GenomeCatalogueGenomes', to='emgapi.GenomeCatalogue'),
        ),
        migrations.AlterUniqueTogether(
            name='genomecataloguegenomes',
            unique_together={('genome', 'genome_catalogue')},
        ),
        migrations.AlterUniqueTogether(
            name='genomecatalogue',
            unique_together={('catalogue_series', 'version')},
        ),
    ]
