# Generated by Django 3.2 on 2021-06-15 09:39
import django
from django.db import migrations, models

downloads = (
    ("Protein sequence FASTA file of the species representative", "Predicted CDS",),
    ("DNA sequence FASTA file of the genome assembly of the species representative", "Nucleic Acid Sequence",),
    ("DNA sequence FASTA file index of the genome assembly of the species representative", "Nucleic Acid Sequence index",),
    ("Protein sequence of the accessory genome", "Protein sequence (accessory)",),
    ("Protein sequence of the core genome", "Protein sequence (core)",),
    ("eggNOG annotations of the protein coding sequences", "EggNog annotation",),
    ("eggNOG annotations of the core and accessory genes", "EggNog annotation (core and accessory)",),
    ("InterProScan annotation of the protein coding sequences", "InterProScan annotation",),
    ("InterProScan annotations of the core and accessory genes", "InterProScan annotation (core and accessory)",),
    ("Presence/absence binary matrix of the pan-genome across all conspecific genomes", "Gene Presence / Absence matrix",),
    ("Protein sequence FASTA file of core genes (>=90% of the " +
     "genomes with >=90% amino acid identity)", "Core predicted CDS",),
    ("Protein sequence FASTA file of accessory genes", "Accessory predicted CDS",),
    ("Protein sequence FASTA file of core and accessory genes", "Core & Accessory predicted CDS",),
    ("Genome GFF file with various sequence annotations", "Genome Annotation"),
    ("Phylogenetic tree of release genomes", 'Phylogenetic tree of release genomes')
)


def change_release_to_catalogue_download_description(apps, schema_editor):
    DownloadDescriptionLabel = apps.get_model("emgapi",
                                              "DownloadDescriptionLabel")
    release_genomes_label = DownloadDescriptionLabel.objects.get(description='Phylogenetic tree of release genomes')
    release_genomes_label.description_label = 'Phylogenetic tree of catalogue genomes'
    release_genomes_label.description = 'Phylogenetic tree of catalogue genomes'
    release_genomes_label.save()


def unchange_release_to_catalogue_download_description(apps, schema_editor):
    DownloadDescriptionLabel = apps.get_model("emgapi",
                                              "DownloadDescriptionLabel")
    catalogue_genomes_label = DownloadDescriptionLabel.objects.get(description='Phylogenetic tree of catalogue genomes')
    catalogue_genomes_label.description_label = 'Phylogenetic tree of release genomes'
    catalogue_genomes_label.description = 'Phylogenetic tree of release genomes'
    catalogue_genomes_label.save()


def make_first_release_for_genome_be_only_genome_catalogue(apps, schema_editor):
    Genome = apps.get_model("emgapi", "Genome")
    for genome in Genome.objects.all():
        genome.catalogue_id = genome.releases.first().id


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0032_auto_20210615_0939'),
    ]

    operations = [
        migrations.RenameModel(
            'Release',
            'GenomeCatalogue'
        ),
        migrations.AddField(
            model_name='genome',
            name='catalogue',
            field=models.ForeignKey(db_column='GENOME_CATALOGUE', on_delete=django.db.models.deletion.CASCADE,
                                    to='emgapi.GenomeCatalogue', null=True),
        ),
        migrations.RunPython(
            make_first_release_for_genome_be_only_genome_catalogue,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            change_release_to_catalogue_download_description,
            reverse_code=unchange_release_to_catalogue_download_description),
    ]
