# Generated by Django 3.2.4 on 2021-09-09 20:33

from django.db import migrations

NEW_TYPES = ["hybrid_assembly", "long_reads_assembly"]


def new_experiment_types(apps, schema_editor):
    ExperimentType = apps.get_model("emgapi", "ExperimentType")
    last_id = ExperimentType.objects.latest("experiment_type_id").experiment_type_id
    for new_type in NEW_TYPES:
        last_id += 1
        ExperimentType.objects.get_or_create(
            experiment_type_id=last_id, experiment_type=new_type
        )


def remove_new_experiment_types(apps, schema_editor):
    ExperimentType = apps.get_model("emgapi", "ExperimentType")
    for new_type in NEW_TYPES:
        try:
            et = ExperimentType.objects.get(experiment_type=new_type)
            et.delete()
        except ExperimentType.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("emgapi", "0033_multiple_genome_cats"),
    ]

    operations = [
        migrations.RunPython(new_experiment_types, remove_new_experiment_types),
    ]
