# Generated by Django 3.2.7 on 2021-11-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0033_multiple_genome_cats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genomecataloguedownload',
            unique_together={('realname', 'alias', 'genome_catalogue')},
        ),
    ]
