# Generated by Django 3.2.7 on 2021-11-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0034_alter_genomecataloguedownload_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genome',
            name='pangenome_eggnog_coverage',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='pangenome_ipr_coverage',
        ),
        migrations.RemoveField(
            model_name='genomecogcounts',
            name='pangenome_count',
        ),
        migrations.RemoveField(
            model_name='genomekeggclasscounts',
            name='pangenome_count',
        ),
        migrations.RemoveField(
            model_name='genomekeggmodulecounts',
            name='pangenome_count',
        ),
    ]
