# Generated by Django 3.2.7 on 2021-12-02 14:12

from django.db import migrations


def create_pangenome_download_descriptions(apps, schema_editor):
    DownloadDescriptionLabel = apps.get_model("emgapi", "DownloadDescriptionLabel")

    DownloadDescriptionLabel.objects.create(description='DNA sequence FASTA file of the pangenome',
                                            description_label='Pangenome DNA sequence')
    DownloadDescriptionLabel.objects.create(description='List of core genes in the entire pangenome',
                                            description_label='Pangenome core genes list')


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0035_auto_20211130_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genome',
            name='cmseq',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='taxincons',
        ),
        migrations.RunPython(create_pangenome_download_descriptions, reverse_code=migrations.RunPython.noop),
    ]
