# Generated by Django 3.2.7 on 2021-12-06 11:37

from django.db import migrations


def create_pangenome_download_descriptions(apps, schema_editor):
    DownloadDescriptionLabel = apps.get_model("emgapi", "DownloadDescriptionLabel")

    DownloadDescriptionLabel.objects.create(description='rRNA sequence of the genome species representative',
                                            description_label='Genome rRNA Sequence')


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0036_auto_20211202_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genome',
            name='num_genomes_non_redundant',
        ),
        migrations.RunPython(create_pangenome_download_descriptions, reverse_code=migrations.RunPython.noop),
    ]
