# Generated by Django 3.2.7 on 2022-01-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0037_remove_genome_num_genomes_non_redundant'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_accession', models.CharField(db_column='LEGACY_ACCESSION', db_index=True, max_length=80, verbose_name='Legacy assembly')),
                ('new_accession', models.CharField(db_column='NEW_ACCESSION', max_length=80, verbose_name='New accession')),
                ('legacy_date', models.DateField(blank=True, db_column='LEGACY_DATE', null=True, verbose_name='Legacy date')),
                ('comments', models.CharField(blank=True, db_column='COMMENTS', max_length=200, null=True, verbose_name='Comments')),
            ],
            options={
                'db_table': 'LEGACY_ASSEMBLY',
                'unique_together': {('legacy_accession', 'new_accession')},
            },
        ),
    ]
