# Generated by Django 3.2.7 on 2022-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0038_legacyassembly'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biome',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='biome',
            constraint=models.UniqueConstraint(fields=('lineage', 'biome_name'), name='biome_hier_uniq_lineage'),
        ),
    ]
