# Generated by Django 3.2.12 on 2022-06-09 13:35

from django.db import migrations, models
import emgapi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0038_legacyassembly'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='ena_study_accession',
            field=models.CharField(blank=True, db_column='ENA_STUDY_ACCESSION', help_text='ENA Study accession.', max_length=20, null=True, validators=[emgapi.validators.validate_ena_study_accession]),
        ),
    ]
