# Generated by Django 3.2.12 on 2022-07-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0039_run_ena_study_accession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='is_public',
            field=models.IntegerField(db_column='IS_PUBLIC', default=False),
        ),
    ]
