# Generated by Django 3.2.12 on 2022-07-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0039_run_ena_study_accession'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='is_private',
            field=models.BooleanField(db_column='IS_PRIVATE', default=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='is_suppressed',
            field=models.BooleanField(db_column='IS_SUPRESSED', default=False),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='suppresion_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Draft'), (3, 'Cancelled'), (6, 'Killed'), (7, 'Temporary Suppressed'), (8, 'Temporary Killed')], db_column='REASON', null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='suppressed_at',
            field=models.DateTimeField(blank=True, db_column='SUPRESSED_AT', null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='is_private',
            field=models.BooleanField(db_column='IS_PRIVATE', default=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='is_suppressed',
            field=models.BooleanField(db_column='IS_SUPRESSED', default=False),
        ),
        migrations.AddField(
            model_name='assembly',
            name='suppresion_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Draft'), (3, 'Cancelled'), (6, 'Killed'), (7, 'Temporary Suppressed'), (8, 'Temporary Killed')], db_column='REASON', null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='suppressed_at',
            field=models.DateTimeField(blank=True, db_column='SUPRESSED_AT', null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='is_private',
            field=models.BooleanField(db_column='IS_PRIVATE', default=True),
        ),
        migrations.AddField(
            model_name='run',
            name='is_suppressed',
            field=models.BooleanField(db_column='IS_SUPRESSED', default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='suppresion_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Draft'), (3, 'Cancelled'), (6, 'Killed'), (7, 'Temporary Suppressed'), (8, 'Temporary Killed')], db_column='REASON', null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='suppressed_at',
            field=models.DateTimeField(blank=True, db_column='SUPRESSED_AT', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_private',
            field=models.BooleanField(db_column='IS_PRIVATE', default=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_suppressed',
            field=models.BooleanField(db_column='IS_SUPRESSED', default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='suppresion_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Draft'), (3, 'Cancelled'), (6, 'Killed'), (7, 'Temporary Suppressed'), (8, 'Temporary Killed')], db_column='REASON', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='suppressed_at',
            field=models.DateTimeField(blank=True, db_column='SUPRESSED_AT', null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='is_public',
            field=models.IntegerField(db_column='IS_PUBLIC', default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='is_private',
            field=models.BooleanField(db_column='IS_PRIVATE', default=True),
        ),        
        migrations.AddField(
            model_name='study',
            name='is_suppressed',
            field=models.BooleanField(db_column='IS_SUPRESSED', default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='suppressed_at',
            field=models.DateTimeField(blank=True, db_column='SUPRESSED_AT', null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='suppresion_reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Draft'), (3, 'Cancelled'), (6, 'Killed'), (7, 'Temporary Suppressed'), (8, 'Temporary Killed')], db_column='REASON', null=True),
        ),
    ]
