# Generated by Django 3.2.12 on 2022-07-21 15:23

from django.db import migrations
from django.utils import timezone

# I've copied the value as they may change in the models
DRAFT = 1
PRIVATE = 2
CANCELLED = 3
PUBLIC = 4
SUPPRESSED = 5
KILLED = 6
TEMPORARY_SUPPRESSED = 7
TEMPORARY_KILLED = 8


def migrate_the_status_field(apps, schema_editor):
    """Migrate the Sample, Study, Run, Assembly and AnalysisJob different status fields to
    the new suppressed and private fields.
    """

    suppress = {
        "is_suppressed": True,
        "suppressed_at": timezone.now(),
    }

    Sample = apps.get_model("emgapi", "Sample")
    Study = apps.get_model("emgapi", "Study")
    for model in [Sample, Study]:
        model.objects.filter(is_public=0).update(is_private=True)
        model.objects.filter(is_public=1).update(is_private=False)
        model.objects.filter(is_public=SUPPRESSED).update(**suppress)

    Run = apps.get_model("emgapi", "Run")
    Assembly = apps.get_model("emgapi", "Assembly")
    for model in [Run, Assembly]:
        model.objects.filter(status_id=PRIVATE).update(is_private=True)
        model.objects.filter(status_id=PUBLIC).update(is_private=False)
        for suppression_code in [
            SUPPRESSED,
            KILLED,
            TEMPORARY_SUPPRESSED,
            TEMPORARY_KILLED,
            CANCELLED,
        ]:
            model.objects.filter(status_id=suppression_code).update(
                **dict(suppress, **{"suppresion_reason": suppression_code})
            )

    AnalysisJob = apps.get_model("emgapi", "AnalysisJob")
    AnalysisJob.objects.filter(run_status_id=PRIVATE).update(is_private=True)
    AnalysisJob.objects.filter(run_status_id=PUBLIC).update(is_private=False)
    for suppression_code in [
        SUPPRESSED,
        KILLED,
        TEMPORARY_SUPPRESSED,
        TEMPORARY_KILLED,
        CANCELLED,
    ]:
        AnalysisJob.objects.filter(run_status_id=suppression_code).update(
            **dict(suppress, **{"suppresion_reason": suppression_code})
        )


class Migration(migrations.Migration):
    dependencies = [
        ("emgapi", "0040_auto_20220721_0958"),
    ]

    operations = [
        migrations.RunPython(migrate_the_status_field, migrations.RunPython.noop),
    ]
