# Generated by Django 3.2.12 on 2022-07-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emgapi', '0041_migrate_status_to_suppressed_and_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisjob',
            name='run_status_id',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='status_id',
        ),
        migrations.RemoveField(
            model_name='run',
            name='status_id',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='study',
            name='is_public',
        ),        
    ]
