emg:
  databases:
    default:
      ENGINE: 'django.db.backends.mysql'
      NAME: emg
      USER: root
      HOST: mysql
      PORT: 3306

  admin: True
  auth_backends: 
    - 'emgapi.backends.EMGBackend'
    - 'django.contrib.auth.backends.ModelBackend'

  cors_origin_allow_all: true
  debug: true
  results_dir: '/opt/results'
  static_root: '/opt/staticfiles'
  emg_backend_auth: 'https://www.ebi.ac.uk/ena/auth/login'
  secure_cookies: false

  mongodb:
    db: emg
    host: mongodb

  sourmash:
    signatures_path: '/tmp/signatures'
    results_path: '/tmp/results'
    celery_broker: 'redis://localhost:6379/0'
    celery_backend: 'redis://localhost:6379/1'