emg:
  databases:
    default:
      ENGINE: 'django.db.backends.mysql'
      NAME: emg
      USER: root
      HOST: mysql
      PORT: 3306

  admin: True
  downloads_bypass_nginx: True
  auth_backends: 
    - 'emgapi.backends.EMGBackend'
    - 'django.contrib.auth.backends.ModelBackend'

  cors_origin_allow_all: true
  debug: true
  results_dir: '/opt/emgapi/results'
  static_root: '/opt/emgapi/staticfiles'
  emg_backend_auth: 'https://www.ebi.ac.uk/ena/auth/login'
  secure_cookies: false

  mongodb:
    db: emg
    host: mongodb

  documentation:
    title: 'MGnify API'
    external_docs_url: 'https://emg-docs.readthedocs.io/en/latest/api.html'
    external_docs_description: 'MGnify documentation – API section'
    description:
      >
        General MGnify documentation is available on Read the Docs:
        https://emg-docs.readthedocs.io/