emg:
  databases:
    default:
      ENGINE: 'django.db.backends.sqlite3'
      NAME: '/opt/ci/testdbs/emg-testdb-tests.sqlite'

  session_engine: 'django.contrib.sessions.backends.cache'
  emg_backend_auth: "https://backend"
  mongodb:
      db: emg_tests
      host: mongodb
  sourmash:
    signatures_path: 'fixtures/'
    results_path: 'fixtures/'
    celery_broker: 'redis://localhost:6379/0'
    celery_backend: 'redis://localhost:6379/1'
  results_production_dir: '/dummy/path/results'
  # metagenomics exchange
  me_api: 'https://wwwdev.ebi.ac.uk/ena/registry/metagenome/api'
  ena_api_password: None