emg:
  databases:
    default:
      ENGINE: 'django.db.backends.mysql'
      NAME: emg
      USER: root
      HOST: mysql
      PORT: 3306

  admin: False
  auth_backends: 
    - 'emgapi.backends.EMGBackend'
    - 'django.contrib.auth.backends.ModelBackend'

  allowed_host: '*'
  debug: true
  prefix: '/metagenomics/api'
  results_dir: '/opt/results'
  static_root: '/opt/staticfiles'
  emg_backend_auth: 'https://www.ebi.ac.uk/ena/auth/login'
  secure_cookies: false

  mongodb:
    db: emg
    host: mongodb
