emg:
  databases:
    default:
      ENGINE: 'django.db.backends.mysql'
      NAME: 'emg_tests'
      USER: 'root'
      HOST: mysql
      PORT: 3306
  session_engine: 'django.contrib.sessions.backends.cache'
  emg_backend_auth: "https://backend"
  mongodb:
      db: emg_tests
      host: mongodb
