emg:
  databases:
    default:
      ENGINE: 'django.db.backends.mysql'
      NAME: 'emg'
      USER: 'root'
      PASSWORD: 'root'
      HOST: 127.0.0.1
      PORT: 3306
  session_engine: 'django.contrib.sessions.backends.cache'
  emg_backend_auth: "https://backend"
  mongodb:
      db: 'testdb'
      host: '127.0.0.1'
  sourmash:
    signatures_path: 'fixtures/'
    results_path: 'fixtures/'
    celery_broker: 'redis://localhost:6379/0'
    celery_backend: 'redis://localhost:6379/1'
  results_production_dir: '/dummy/path/results'
  # metagenomics exchange
  me_api: 'http://wp-np2-5c.ebi.ac.uk:8080/ena/registry/metagenome/api'
  me_api_token: 'mgx 871cd915-2826-46bb-94ed-8e6a3d9b6014 '