/*
-- Query: SELECT * FROM BIOME_HIERARCHY_TREE
-- Date: 2018-11-21 11:04
*/
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (0,'root',1,984,1,'root');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (1,'Engineered',2,161,2,'root:Engineered');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (2,'Biogas plant',3,6,3,'root:Engineered:Biogas plant');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (3,'Wet fermentation',4,5,4,'root:Engineered:Biogas plant:Wet fermentation');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (4,'Bioreactor',7,18,3,'root:Engineered:Bioreactor');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (5,'Continuous culture',8,17,4,'root:Engineered:Bioreactor:Continuous culture');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (6,'Marine intertidal flat sediment inoculum',9,12,5,'root:Engineered:Bioreactor:Continuous culture:Marine intertidal flat sediment inoculum');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (7,'Wadden Sea-Germany',10,11,6,'root:Engineered:Bioreactor:Continuous culture:Marine intertidal flat sediment inoculum:Wadden Sea-Germany');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (8,'Marine sediment inoculum',13,16,5,'root:Engineered:Bioreactor:Continuous culture:Marine sediment inoculum');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (9,'Wadden Sea-Germany',14,15,6,'root:Engineered:Bioreactor:Continuous culture:Marine sediment inoculum:Wadden Sea-Germany');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (10,'Bioremediation',19,50,3,'root:Engineered:Bioremediation');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (11,'Hydrocarbon',20,25,4,'root:Engineered:Bioremediation:Hydrocarbon');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (12,'Benzene',21,24,5,'root:Engineered:Bioremediation:Hydrocarbon:Benzene');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (13,'Bioreactor',22,23,6,'root:Engineered:Bioremediation:Hydrocarbon:Benzene:Bioreactor');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (14,'Metal',26,27,4,'root:Engineered:Bioremediation:Metal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (15,'Persistent organic pollutants (POP)',28,31,4,'root:Engineered:Bioremediation:Persistent organic pollutants (POP)');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (16,'Polycyclic aromatic hydrocarbons',29,30,5,'root:Engineered:Bioremediation:Persistent organic pollutants (POP):Polycyclic aromatic hydrocarbons');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (17,'Terephthalate',32,39,4,'root:Engineered:Bioremediation:Terephthalate');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (18,'Wastewater',33,38,5,'root:Engineered:Bioremediation:Terephthalate:Wastewater');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (19,'Activated sludge',34,35,6,'root:Engineered:Bioremediation:Terephthalate:Wastewater:Activated sludge');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (20,'Bioreactor',36,37,6,'root:Engineered:Bioremediation:Terephthalate:Wastewater:Bioreactor');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (21,'Tetrachloroethylene and derivatives',40,49,4,'root:Engineered:Bioremediation:Tetrachloroethylene and derivatives');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (22,'Chloroethene',41,44,5,'root:Engineered:Bioremediation:Tetrachloroethylene and derivatives:Chloroethene');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (23,'Bioreactor',42,43,6,'root:Engineered:Bioremediation:Tetrachloroethylene and derivatives:Chloroethene:Bioreactor');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (24,'Tetrachloroethylene',45,48,5,'root:Engineered:Bioremediation:Tetrachloroethylene and derivatives:Tetrachloroethylene');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (25,'Bioreactor',46,47,6,'root:Engineered:Bioremediation:Tetrachloroethylene and derivatives:Tetrachloroethylene:Bioreactor');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (26,'Biotransformation',51,58,3,'root:Engineered:Biotransformation');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (27,'Microbial enhanced oil recovery',52,53,4,'root:Engineered:Biotransformation:Microbial enhanced oil recovery');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (28,'Microbial solubilization of coal',54,55,4,'root:Engineered:Biotransformation:Microbial solubilization of coal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (29,'Mixed alcohol bioreactor',56,57,4,'root:Engineered:Biotransformation:Mixed alcohol bioreactor');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (30,'Built environment',59,60,3,'root:Engineered:Built environment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (31,'Food production',61,72,3,'root:Engineered:Food production');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (32,'Dairy products',62,63,4,'root:Engineered:Food production:Dairy products');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (33,'Fermented beverages',64,65,4,'root:Engineered:Food production:Fermented beverages');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (34,'Fermented seafood',66,67,4,'root:Engineered:Food production:Fermented seafood');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (35,'Fermented vegetables',68,69,4,'root:Engineered:Food production:Fermented vegetables');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (36,'Silage fermentation',70,71,4,'root:Engineered:Food production:Silage fermentation');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (37,'Industrial production',73,76,3,'root:Engineered:Industrial production');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (38,'Engineered product',74,75,4,'root:Engineered:Industrial production:Engineered product');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (39,'Lab enrichment',77,90,3,'root:Engineered:Lab enrichment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (40,'Defined media',78,87,4,'root:Engineered:Lab enrichment:Defined media');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (41,'Aerobic media',79,80,5,'root:Engineered:Lab enrichment:Defined media:Aerobic media');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (42,'Anaerobic media',81,82,5,'root:Engineered:Lab enrichment:Defined media:Anaerobic media');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (43,'Marine media',83,86,5,'root:Engineered:Lab enrichment:Defined media:Marine media');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (44,'Algoconsortia',84,85,6,'root:Engineered:Lab enrichment:Defined media:Marine media:Algoconsortia');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (45,'Undefined media',88,89,4,'root:Engineered:Lab enrichment:Undefined media');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (46,'Lab Synthesis',91,94,3,'root:Engineered:Lab Synthesis');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (47,'Genetic cross',92,93,4,'root:Engineered:Lab Synthesis:Genetic cross');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (48,'Modeled',95,104,3,'root:Engineered:Modeled');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (49,'Simulated communities (DNA mixture)',96,97,4,'root:Engineered:Modeled:Simulated communities (DNA mixture)');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (50,'Simulated communities (microbial mixture)',98,99,4,'root:Engineered:Modeled:Simulated communities (microbial mixture)');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (51,'Simulated communities (sequence read mixture)',100,103,4,'root:Engineered:Modeled:Simulated communities (sequence read mixture)');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (52,'Sanger',101,102,5,'root:Engineered:Modeled:Simulated communities (sequence read mixture):Sanger');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (53,'Solid waste',105,122,3,'root:Engineered:Solid waste');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (54,'Composting',106,117,4,'root:Engineered:Solid waste:Composting');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (55,'Grass',107,110,5,'root:Engineered:Solid waste:Composting:Grass');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (56,'Bioreactor',108,109,6,'root:Engineered:Solid waste:Composting:Grass:Bioreactor');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (57,'Bioreactor',111,112,5,'root:Engineered:Solid waste:Composting:Bioreactor');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (58,'Wood',113,116,5,'root:Engineered:Solid waste:Composting:Wood');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (59,'Bioreactor',114,115,6,'root:Engineered:Solid waste:Composting:Wood:Bioreactor');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (60,'Landfill',118,119,4,'root:Engineered:Solid waste:Landfill');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (61,'Solid animal waste',120,121,4,'root:Engineered:Solid waste:Solid animal waste');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (62,'Wastewater',123,160,3,'root:Engineered:Wastewater');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (63,'Activated Sludge',124,125,4,'root:Engineered:Wastewater:Activated Sludge');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (64,'Industrial wastewater',126,137,4,'root:Engineered:Wastewater:Industrial wastewater');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (65,'Agricultural wastewater',127,128,5,'root:Engineered:Wastewater:Industrial wastewater:Agricultural wastewater');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (66,'Landfill leachate',129,130,5,'root:Engineered:Wastewater:Industrial wastewater:Landfill leachate');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (67,'Mine water',131,132,5,'root:Engineered:Wastewater:Industrial wastewater:Mine water');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (68,'Petrochemical',133,134,5,'root:Engineered:Wastewater:Industrial wastewater:Petrochemical');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (69,'Pulp and paper wastewater',135,136,5,'root:Engineered:Wastewater:Industrial wastewater:Pulp and paper wastewater');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (70,'Nutrient removal',138,157,4,'root:Engineered:Wastewater:Nutrient removal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (71,'Biological phosphorus removal',139,144,5,'root:Engineered:Wastewater:Nutrient removal:Biological phosphorus removal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (72,'Activated sludge',140,141,6,'root:Engineered:Wastewater:Nutrient removal:Biological phosphorus removal:Activated sludge');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (73,'Bioreactor',142,143,6,'root:Engineered:Wastewater:Nutrient removal:Biological phosphorus removal:Bioreactor');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (74,'Dissolved organics (aerobic)',145,148,5,'root:Engineered:Wastewater:Nutrient removal:Dissolved organics (aerobic)');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (75,'Activated sludge',146,147,6,'root:Engineered:Wastewater:Nutrient removal:Dissolved organics (aerobic):Activated sludge');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (76,'Dissolved organics (anaerobic)',149,152,5,'root:Engineered:Wastewater:Nutrient removal:Dissolved organics (anaerobic)');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (77,'Activated sludge',150,151,6,'root:Engineered:Wastewater:Nutrient removal:Dissolved organics (anaerobic):Activated sludge');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (78,'Nitrogen removal',153,156,5,'root:Engineered:Wastewater:Nutrient removal:Nitrogen removal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (79,'Anammox',154,155,6,'root:Engineered:Wastewater:Nutrient removal:Nitrogen removal:Anammox');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (80,'Water and sludge',158,159,4,'root:Engineered:Wastewater:Water and sludge');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (81,'Environmental',162,513,2,'root:Environmental');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (82,'Air',163,168,3,'root:Environmental:Air');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (83,'Indoor Air',164,165,4,'root:Environmental:Air:Indoor Air');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (84,'Outdoor Air',166,167,4,'root:Environmental:Air:Outdoor Air');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (85,'Aquatic',169,418,3,'root:Environmental:Aquatic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (86,'Aquaculture',170,171,4,'root:Environmental:Aquatic:Aquaculture');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (87,'Estuary',172,175,4,'root:Environmental:Aquatic:Estuary');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (88,'Sediment',173,174,5,'root:Environmental:Aquatic:Estuary:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (89,'Freshwater',176,257,4,'root:Environmental:Aquatic:Freshwater');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (90,'Drinking water',177,182,5,'root:Environmental:Aquatic:Freshwater:Drinking water');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (91,'Chlorinated',178,179,6,'root:Environmental:Aquatic:Freshwater:Drinking water:Chlorinated');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (92,'Delivery networks',180,181,6,'root:Environmental:Aquatic:Freshwater:Drinking water:Delivery networks');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (93,'Groundwater',183,198,5,'root:Environmental:Aquatic:Freshwater:Groundwater');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (94,'Acid Mine Drainage',184,185,6,'root:Environmental:Aquatic:Freshwater:Groundwater:Acid Mine Drainage');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (95,'Biofilm',186,187,6,'root:Environmental:Aquatic:Freshwater:Groundwater:Biofilm');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (96,'Cave water',188,189,6,'root:Environmental:Aquatic:Freshwater:Groundwater:Cave water');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (97,'Coalbed water',190,191,6,'root:Environmental:Aquatic:Freshwater:Groundwater:Coalbed water');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (98,'Contaminated',192,193,6,'root:Environmental:Aquatic:Freshwater:Groundwater:Contaminated');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (99,'Mine',194,195,6,'root:Environmental:Aquatic:Freshwater:Groundwater:Mine');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (100,'Mine drainage',196,197,6,'root:Environmental:Aquatic:Freshwater:Groundwater:Mine drainage');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (101,'Ice',199,206,5,'root:Environmental:Aquatic:Freshwater:Ice');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (102,'Glacial lake',200,201,6,'root:Environmental:Aquatic:Freshwater:Ice:Glacial lake');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (103,'Glacier',202,203,6,'root:Environmental:Aquatic:Freshwater:Ice:Glacier');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (104,'Ice accretions',204,205,6,'root:Environmental:Aquatic:Freshwater:Ice:Ice accretions');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (105,'Lake',207,208,5,'root:Environmental:Aquatic:Freshwater:Lake');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (106,'Lentic',209,220,5,'root:Environmental:Aquatic:Freshwater:Lentic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (107,'Epilimnion',210,211,6,'root:Environmental:Aquatic:Freshwater:Lentic:Epilimnion');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (108,'Hypolimnion',212,213,6,'root:Environmental:Aquatic:Freshwater:Lentic:Hypolimnion');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (109,'Limnetic zone',214,215,6,'root:Environmental:Aquatic:Freshwater:Lentic:Limnetic zone');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (110,'Littoral zone',216,217,6,'root:Environmental:Aquatic:Freshwater:Lentic:Littoral zone');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (111,'Sediment',218,219,6,'root:Environmental:Aquatic:Freshwater:Lentic:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (112,'Lotic',221,232,5,'root:Environmental:Aquatic:Freshwater:Lotic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (113,'Acidic',222,223,6,'root:Environmental:Aquatic:Freshwater:Lotic:Acidic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (114,'Low land river systems',224,225,6,'root:Environmental:Aquatic:Freshwater:Lotic:Low land river systems');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (115,'Microbial mats',226,227,6,'root:Environmental:Aquatic:Freshwater:Lotic:Microbial mats');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (116,'Mid stream',228,229,6,'root:Environmental:Aquatic:Freshwater:Lotic:Mid stream');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (117,'Sediment',230,231,6,'root:Environmental:Aquatic:Freshwater:Lotic:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (118,'Microbialites',233,234,5,'root:Environmental:Aquatic:Freshwater:Microbialites');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (119,'Pond',235,238,5,'root:Environmental:Aquatic:Freshwater:Pond');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (120,'Sediment',236,237,6,'root:Environmental:Aquatic:Freshwater:Pond:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (121,'Sediment',239,240,5,'root:Environmental:Aquatic:Freshwater:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (122,'Storm water',241,244,5,'root:Environmental:Aquatic:Freshwater:Storm water');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (123,'Drainage pipe biofilm',242,243,6,'root:Environmental:Aquatic:Freshwater:Storm water:Drainage pipe biofilm');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (124,'Subglacial lake',245,246,5,'root:Environmental:Aquatic:Freshwater:Subglacial lake');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (125,'Wetlands',247,256,5,'root:Environmental:Aquatic:Freshwater:Wetlands');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (126,'Bog',248,249,6,'root:Environmental:Aquatic:Freshwater:Wetlands:Bog');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (127,'Marsh',250,251,6,'root:Environmental:Aquatic:Freshwater:Wetlands:Marsh');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (128,'Sediment',252,253,6,'root:Environmental:Aquatic:Freshwater:Wetlands:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (129,'Swamp',254,255,6,'root:Environmental:Aquatic:Freshwater:Wetlands:Swamp');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (130,'Lentic',258,261,4,'root:Environmental:Aquatic:Lentic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (131,'Brackish',259,260,5,'root:Environmental:Aquatic:Lentic:Brackish');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (132,'Marine',262,347,4,'root:Environmental:Aquatic:Marine');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (133,'Brackish',263,264,5,'root:Environmental:Aquatic:Marine:Brackish');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (134,'Coastal',265,268,5,'root:Environmental:Aquatic:Marine:Coastal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (135,'Sediment',266,267,6,'root:Environmental:Aquatic:Marine:Coastal:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (136,'Cold seeps',269,272,5,'root:Environmental:Aquatic:Marine:Cold seeps');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (137,'Sediment',270,271,6,'root:Environmental:Aquatic:Marine:Cold seeps:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (138,'Fossil',273,276,5,'root:Environmental:Aquatic:Marine:Fossil');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (139,'Whale fall',274,275,6,'root:Environmental:Aquatic:Marine:Fossil:Whale fall');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (140,'Hydrothermal vents',277,286,5,'root:Environmental:Aquatic:Marine:Hydrothermal vents');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (141,'Black smokers',278,279,6,'root:Environmental:Aquatic:Marine:Hydrothermal vents:Black smokers');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (142,'Diffuse flow',280,281,6,'root:Environmental:Aquatic:Marine:Hydrothermal vents:Diffuse flow');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (143,'Microbial mats',282,283,6,'root:Environmental:Aquatic:Marine:Hydrothermal vents:Microbial mats');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (144,'Sediment',284,285,6,'root:Environmental:Aquatic:Marine:Hydrothermal vents:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (145,'Intertidal zone',287,304,5,'root:Environmental:Aquatic:Marine:Intertidal zone');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (146,'Beach',288,289,6,'root:Environmental:Aquatic:Marine:Intertidal zone:Beach');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (147,'Coral reef',290,291,6,'root:Environmental:Aquatic:Marine:Intertidal zone:Coral reef');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (148,'Estuary',292,293,6,'root:Environmental:Aquatic:Marine:Intertidal zone:Estuary');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (149,'Mangrove swamp',294,295,6,'root:Environmental:Aquatic:Marine:Intertidal zone:Mangrove swamp');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (150,'Microbialites',296,297,6,'root:Environmental:Aquatic:Marine:Intertidal zone:Microbialites');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (151,'Oil-contaminated',298,299,6,'root:Environmental:Aquatic:Marine:Intertidal zone:Oil-contaminated');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (152,'Salt marsh',300,301,6,'root:Environmental:Aquatic:Marine:Intertidal zone:Salt marsh');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (153,'Sediment',302,303,6,'root:Environmental:Aquatic:Marine:Intertidal zone:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (154,'Marginal Sea',305,306,5,'root:Environmental:Aquatic:Marine:Marginal Sea');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (155,'Neritic zone',307,312,5,'root:Environmental:Aquatic:Marine:Neritic zone');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (156,'Oil-contaminated sediment',308,309,6,'root:Environmental:Aquatic:Marine:Neritic zone:Oil-contaminated sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (157,'Sediment',310,311,6,'root:Environmental:Aquatic:Marine:Neritic zone:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (158,'Oceanic',313,328,5,'root:Environmental:Aquatic:Marine:Oceanic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (159,'Abyssal plane',314,315,6,'root:Environmental:Aquatic:Marine:Oceanic:Abyssal plane');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (160,'Aphotic zone',316,317,6,'root:Environmental:Aquatic:Marine:Oceanic:Aphotic zone');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (161,'Benthic',318,319,6,'root:Environmental:Aquatic:Marine:Oceanic:Benthic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (162,'Oil-contaminated',320,321,6,'root:Environmental:Aquatic:Marine:Oceanic:Oil-contaminated');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (163,'Oil-contaminated sediments',322,323,6,'root:Environmental:Aquatic:Marine:Oceanic:Oil-contaminated sediments');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (164,'Photic zone',324,325,6,'root:Environmental:Aquatic:Marine:Oceanic:Photic zone');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (165,'Sediment',326,327,6,'root:Environmental:Aquatic:Marine:Oceanic:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (166,'Oil field',329,332,5,'root:Environmental:Aquatic:Marine:Oil field');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (167,'bore hole',330,331,6,'root:Environmental:Aquatic:Marine:Oil field:bore hole');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (168,'Oil seeps',333,334,5,'root:Environmental:Aquatic:Marine:Oil seeps');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (169,'Pelagic',335,336,5,'root:Environmental:Aquatic:Marine:Pelagic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (170,'Oil-contaminated sediment',337,338,5,'root:Environmental:Aquatic:Marine:Oil-contaminated sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (171,'Sediment',339,340,5,'root:Environmental:Aquatic:Marine:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (172,'Volcanic',341,342,5,'root:Environmental:Aquatic:Marine:Volcanic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (173,'Wetlands',343,346,5,'root:Environmental:Aquatic:Marine:Wetlands');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (174,'Sediment',344,345,6,'root:Environmental:Aquatic:Marine:Wetlands:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (175,'Meromictic lake',348,349,4,'root:Environmental:Aquatic:Meromictic lake');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (176,'Non-marine Saline and Alkaline',350,387,4,'root:Environmental:Aquatic:Non-marine Saline and Alkaline');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (177,'Alkaline',351,358,5,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Alkaline');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (178,'Carbonate',352,353,6,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Alkaline:Carbonate');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (179,'Microbial mats',354,355,6,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Alkaline:Microbial mats');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (180,'Sediment',356,357,6,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Alkaline:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (181,'Hypersaline',359,364,5,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Hypersaline');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (182,'Microbial mats',360,361,6,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Hypersaline:Microbial mats');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (183,'Sediment',362,363,6,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Hypersaline:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (184,'Near-boiling (>90C)',365,368,5,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Near-boiling (>90C)');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (185,'Alkaline',366,367,6,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Near-boiling (>90C):Alkaline');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (186,'Saline',369,382,5,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (187,'Athalassic',370,371,6,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Athalassic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (188,'Epilimnion',372,373,6,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Epilimnion');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (189,'Hypolimnion',374,375,6,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Hypolimnion');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (190,'Microbial mats',376,377,6,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Microbial mats');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (191,'Sediment',378,379,6,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (192,'Thalassic',380,381,6,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Saline:Thalassic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (193,'Salt crystallizer pond',383,386,5,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Salt crystallizer pond');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (194,'Microbial mats',384,385,6,'root:Environmental:Aquatic:Non-marine Saline and Alkaline:Salt crystallizer pond:Microbial mats');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (195,'Sediment',388,389,4,'root:Environmental:Aquatic:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (196,'Thermal springs',390,417,4,'root:Environmental:Aquatic:Thermal springs');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (197,'Hot (42-90C)',391,400,5,'root:Environmental:Aquatic:Thermal springs:Hot (42-90C)');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (198,'Acidic',392,393,6,'root:Environmental:Aquatic:Thermal springs:Hot (42-90C):Acidic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (199,'Alkaline',394,395,6,'root:Environmental:Aquatic:Thermal springs:Hot (42-90C):Alkaline');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (200,'Neutral',396,397,6,'root:Environmental:Aquatic:Thermal springs:Hot (42-90C):Neutral');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (201,'Sediment',398,399,6,'root:Environmental:Aquatic:Thermal springs:Hot (42-90C):Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (202,'Near-boiling (>90C)',401,404,5,'root:Environmental:Aquatic:Thermal springs:Near-boiling (>90C)');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (203,'Alkaline',402,403,6,'root:Environmental:Aquatic:Thermal springs:Near-boiling (>90C):Alkaline');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (204,'Sediment',405,406,5,'root:Environmental:Aquatic:Thermal springs:Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (205,'Tepid (25-34C)',407,410,5,'root:Environmental:Aquatic:Thermal springs:Tepid (25-34C)');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (206,'Sediment',408,409,6,'root:Environmental:Aquatic:Thermal springs:Tepid (25-34C):Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (207,'Warm (34-42C)',411,416,5,'root:Environmental:Aquatic:Thermal springs:Warm (34-42C)');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (208,'Neutral',412,413,6,'root:Environmental:Aquatic:Thermal springs:Warm (34-42C):Neutral');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (209,'Sediment',414,415,6,'root:Environmental:Aquatic:Thermal springs:Warm (34-42C):Sediment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (210,'Terrestrial',419,512,3,'root:Environmental:Terrestrial');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (211,'Agricultural field',420,421,4,'root:Environmental:Terrestrial:Agricultural field');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (212,'Asphalt lakes',422,425,4,'root:Environmental:Terrestrial:Asphalt lakes');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (213,'Tar',423,424,5,'root:Environmental:Terrestrial:Asphalt lakes:Tar');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (214,'Deep subsurface',426,429,4,'root:Environmental:Terrestrial:Deep subsurface');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (215,'Clay',427,428,5,'root:Environmental:Terrestrial:Deep subsurface:Clay');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (216,'Geologic',430,433,4,'root:Environmental:Terrestrial:Geologic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (217,'Mine',431,432,5,'root:Environmental:Terrestrial:Geologic:Mine');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (218,'Oil reservoir',434,435,4,'root:Environmental:Terrestrial:Oil reservoir');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (219,'Rock-dwelling (subaerial biofilm)',436,437,4,'root:Environmental:Terrestrial:Rock-dwelling (subaerial biofilm)');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (220,'Soil',438,507,4,'root:Environmental:Terrestrial:Soil');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (221,'Clay',439,448,5,'root:Environmental:Terrestrial:Soil:Clay');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (222,'Agricultural land',440,441,6,'root:Environmental:Terrestrial:Soil:Clay:Agricultural land');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (223,'Contaminated',442,443,6,'root:Environmental:Terrestrial:Soil:Clay:Contaminated');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (224,'Grasslands',444,445,6,'root:Environmental:Terrestrial:Soil:Clay:Grasslands');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (225,'Oil-contaminated',446,447,6,'root:Environmental:Terrestrial:Soil:Clay:Oil-contaminated');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (226,'Crop',449,452,5,'root:Environmental:Terrestrial:Soil:Crop');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (227,'Agricultural land',450,451,6,'root:Environmental:Terrestrial:Soil:Crop:Agricultural land');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (228,'Loam',453,462,5,'root:Environmental:Terrestrial:Soil:Loam');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (229,'Agricultural',454,455,6,'root:Environmental:Terrestrial:Soil:Loam:Agricultural');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (230,'Contaminated',456,457,6,'root:Environmental:Terrestrial:Soil:Loam:Contaminated');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (231,'Forest soil',458,459,6,'root:Environmental:Terrestrial:Soil:Loam:Forest soil');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (232,'Grasslands',460,461,6,'root:Environmental:Terrestrial:Soil:Loam:Grasslands');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (233,'Sand',463,472,5,'root:Environmental:Terrestrial:Soil:Sand');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (234,'Desert',464,465,6,'root:Environmental:Terrestrial:Soil:Sand:Desert');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (235,'Forest soil',466,467,6,'root:Environmental:Terrestrial:Soil:Sand:Forest soil');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (236,'Grasslands',468,469,6,'root:Environmental:Terrestrial:Soil:Sand:Grasslands');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (237,'Oil-contaminated',470,471,6,'root:Environmental:Terrestrial:Soil:Sand:Oil-contaminated');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (238,'Silt',473,474,5,'root:Environmental:Terrestrial:Soil:Silt');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (239,'Agricultural',475,476,5,'root:Environmental:Terrestrial:Soil:Agricultural');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (240,'Boreal forest',477,478,5,'root:Environmental:Terrestrial:Soil:Boreal forest');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (241,'Contaminated',479,480,5,'root:Environmental:Terrestrial:Soil:Contaminated');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (242,'Desert',481,482,5,'root:Environmental:Terrestrial:Soil:Desert');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (243,'Forest soil',483,484,5,'root:Environmental:Terrestrial:Soil:Forest soil');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (244,'Grasslands',485,486,5,'root:Environmental:Terrestrial:Soil:Grasslands');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (245,'Mine',487,488,5,'root:Environmental:Terrestrial:Soil:Mine');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (246,'Mine drainage',489,490,5,'root:Environmental:Terrestrial:Soil:Mine drainage');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (247,'Oil-contaminated',491,492,5,'root:Environmental:Terrestrial:Soil:Oil-contaminated');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (248,'Permafrost',493,494,5,'root:Environmental:Terrestrial:Soil:Permafrost');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (249,'Shrubland',495,496,5,'root:Environmental:Terrestrial:Soil:Shrubland');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (250,'Tropical rainforest',497,498,5,'root:Environmental:Terrestrial:Soil:Tropical rainforest');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (251,'Uranium contaminated',499,500,5,'root:Environmental:Terrestrial:Soil:Uranium contaminated');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (252,'Viriome',501,502,5,'root:Environmental:Terrestrial:Soil:Viriome');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (253,'Wetlands',503,506,5,'root:Environmental:Terrestrial:Soil:Wetlands');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (254,'Permafrost',504,505,6,'root:Environmental:Terrestrial:Soil:Wetlands:Permafrost');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (255,'Volcanic',508,511,4,'root:Environmental:Terrestrial:Volcanic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (256,'Fumaroles',509,510,5,'root:Environmental:Terrestrial:Volcanic:Fumaroles');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (257,'Host-associated',514,981,2,'root:Host-associated');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (258,'Algae',515,526,3,'root:Host-associated:Algae');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (259,'Brown Algae',516,517,4,'root:Host-associated:Algae:Brown Algae');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (260,'Green algae',518,521,4,'root:Host-associated:Algae:Green algae');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (261,'Ectosymbionts',519,520,5,'root:Host-associated:Algae:Green algae:Ectosymbionts');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (262,'Red algae',522,525,4,'root:Host-associated:Algae:Red algae');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (263,'Ectosymbionts ',523,524,5,'root:Host-associated:Algae:Red algae:Ectosymbionts ');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (264,'Amphibia',527,532,3,'root:Host-associated:Amphibia');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (265,'Digestive system',528,529,4,'root:Host-associated:Amphibia:Digestive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (266,'Excretory system',530,531,4,'root:Host-associated:Amphibia:Excretory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (267,'Animal',533,552,3,'root:Host-associated:Animal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (268,'Circulatory system',534,535,4,'root:Host-associated:Animal:Circulatory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (269,'Digestive system',536,539,4,'root:Host-associated:Animal:Digestive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (270,'Fecal',537,538,5,'root:Host-associated:Animal:Digestive system:Fecal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (271,'Fossil',540,545,4,'root:Host-associated:Animal:Fossil');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (272,'Bone',541,542,5,'root:Host-associated:Animal:Fossil:Bone');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (273,'Feces',543,544,5,'root:Host-associated:Animal:Fossil:Feces');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (274,'Reproductive system',546,547,4,'root:Host-associated:Animal:Reproductive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (275,'Respiratory system',548,549,4,'root:Host-associated:Animal:Respiratory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (276,'Skin',550,551,4,'root:Host-associated:Animal:Skin');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (277,'Annelida',553,580,3,'root:Host-associated:Annelida');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (278,'Digestive system',554,559,4,'root:Host-associated:Annelida:Digestive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (279,'Digestive tube',555,558,5,'root:Host-associated:Annelida:Digestive system:Digestive tube');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (280,'Extracellular symbionts',556,557,6,'root:Host-associated:Annelida:Digestive system:Digestive tube:Extracellular symbionts');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (281,'Integument',560,569,4,'root:Host-associated:Annelida:Integument');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (282,'Cuticle',561,564,5,'root:Host-associated:Annelida:Integument:Cuticle');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (283,'Epibionts',562,563,6,'root:Host-associated:Annelida:Integument:Cuticle:Epibionts');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (284,'Subcuticular space',565,568,5,'root:Host-associated:Annelida:Integument:Subcuticular space');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (285,'Extracellular symbionts',566,567,6,'root:Host-associated:Annelida:Integument:Subcuticular space:Extracellular symbionts');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (286,'Intracellular endosymbionts',570,573,4,'root:Host-associated:Annelida:Intracellular endosymbionts');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (287,'Trophosome',571,572,5,'root:Host-associated:Annelida:Intracellular endosymbionts:Trophosome');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (288,'Reproductive system',574,579,4,'root:Host-associated:Annelida:Reproductive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (289,'Egg capsule',575,578,5,'root:Host-associated:Annelida:Reproductive system:Egg capsule');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (290,'Extracellular',576,577,6,'root:Host-associated:Annelida:Reproductive system:Egg capsule:Extracellular');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (291,'Arthropoda',581,636,3,'root:Host-associated:Arthropoda');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (292,'Digestive system',582,603,4,'root:Host-associated:Arthropoda:Digestive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (293,'Foregut',583,584,5,'root:Host-associated:Arthropoda:Digestive system:Foregut');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (294,'Gut',585,590,5,'root:Host-associated:Arthropoda:Digestive system:Gut');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (295,'P3 segment',586,587,6,'root:Host-associated:Arthropoda:Digestive system:Gut:P3 segment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (296,'Proctodeal segment',588,589,6,'root:Host-associated:Arthropoda:Digestive system:Gut:Proctodeal segment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (297,'Hindgut',591,596,5,'root:Host-associated:Arthropoda:Digestive system:Hindgut');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (298,'P1 segment',592,593,6,'root:Host-associated:Arthropoda:Digestive system:Hindgut:P1 segment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (299,'P3 segment',594,595,6,'root:Host-associated:Arthropoda:Digestive system:Hindgut:P3 segment');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (300,'Midgut',597,598,5,'root:Host-associated:Arthropoda:Digestive system:Midgut');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (301,'Oral',599,602,5,'root:Host-associated:Arthropoda:Digestive system:Oral');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (302,'Saliva',600,601,6,'root:Host-associated:Arthropoda:Digestive system:Oral:Saliva');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (303,'Integument',604,609,4,'root:Host-associated:Arthropoda:Integument');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (304,'Cuticle',605,608,5,'root:Host-associated:Arthropoda:Integument:Cuticle');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (305,'Thoracic segments',606,607,6,'root:Host-associated:Arthropoda:Integument:Cuticle:Thoracic segments');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (306,'Intracellular endosymbionts',610,617,4,'root:Host-associated:Arthropoda:Intracellular endosymbionts');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (307,'Primary',611,614,5,'root:Host-associated:Arthropoda:Intracellular endosymbionts:Primary');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (308,'Bacteriomes',612,613,6,'root:Host-associated:Arthropoda:Intracellular endosymbionts:Primary:Bacteriomes');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (309,'Secondary',615,616,5,'root:Host-associated:Arthropoda:Intracellular endosymbionts:Secondary');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (310,'Oral cavity',618,619,4,'root:Host-associated:Arthropoda:Oral cavity');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (311,'Respiratory system',620,623,4,'root:Host-associated:Arthropoda:Respiratory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (312,'Gills',621,622,5,'root:Host-associated:Arthropoda:Respiratory system:Gills');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (313,'Symbiotic fungal gardens and galleries',624,631,4,'root:Host-associated:Arthropoda:Symbiotic fungal gardens and galleries');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (314,'Fungus gallery',625,626,5,'root:Host-associated:Arthropoda:Symbiotic fungal gardens and galleries:Fungus gallery');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (315,'Fungus garden',627,630,5,'root:Host-associated:Arthropoda:Symbiotic fungal gardens and galleries:Fungus garden');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (316,'Garden dump',628,629,6,'root:Host-associated:Arthropoda:Symbiotic fungal gardens and galleries:Fungus garden:Garden dump');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (317,'Venom gland',632,635,4,'root:Host-associated:Arthropoda:Venom gland');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (318,'Venom',633,634,5,'root:Host-associated:Arthropoda:Venom gland:Venom');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (319,'Birds',637,668,3,'root:Host-associated:Birds');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (320,'Circulatory system',638,641,4,'root:Host-associated:Birds:Circulatory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (321,'Blood',639,640,5,'root:Host-associated:Birds:Circulatory system:Blood');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (322,'Digestive system',642,661,4,'root:Host-associated:Birds:Digestive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (323,'Ceca',643,646,5,'root:Host-associated:Birds:Digestive system:Ceca');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (324,'Lumen',644,645,6,'root:Host-associated:Birds:Digestive system:Ceca:Lumen');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (325,'Crop',647,650,5,'root:Host-associated:Birds:Digestive system:Crop');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (326,'Lumen',648,649,6,'root:Host-associated:Birds:Digestive system:Crop:Lumen');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (327,'Digestive tube',651,654,5,'root:Host-associated:Birds:Digestive system:Digestive tube');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (328,'Cecum',652,653,6,'root:Host-associated:Birds:Digestive system:Digestive tube:Cecum');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (329,'Fecal',655,656,5,'root:Host-associated:Birds:Digestive system:Fecal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (330,'Small intestine',657,660,5,'root:Host-associated:Birds:Digestive system:Small intestine');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (331,'Duodenal',658,659,6,'root:Host-associated:Birds:Digestive system:Small intestine:Duodenal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (332,'Reproductive system',662,663,4,'root:Host-associated:Birds:Reproductive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (333,'Respiratory system',664,667,4,'root:Host-associated:Birds:Respiratory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (334,'Lungs',665,666,5,'root:Host-associated:Birds:Respiratory system:Lungs');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (335,'Cnidaria',669,670,3,'root:Host-associated:Cnidaria');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (336,'Echinodermata',671,672,3,'root:Host-associated:Echinodermata');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (337,'Endosymbionts',673,678,3,'root:Host-associated:Endosymbionts');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (338,'Fungi',674,677,4,'root:Host-associated:Endosymbionts:Fungi');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (339,'Endosymbionts',675,676,5,'root:Host-associated:Endosymbionts:Fungi:Endosymbionts');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (340,'Fish',679,702,3,'root:Host-associated:Fish');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (341,'Circulatory system',680,683,4,'root:Host-associated:Fish:Circulatory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (342,'Blood',681,682,5,'root:Host-associated:Fish:Circulatory system:Blood');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (343,'Digestive system',684,691,4,'root:Host-associated:Fish:Digestive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (344,'Foregut',685,688,5,'root:Host-associated:Fish:Digestive system:Foregut');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (345,'Uncharacterized',686,687,6,'root:Host-associated:Fish:Digestive system:Foregut:Uncharacterized');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (346,'Intestine',689,690,5,'root:Host-associated:Fish:Digestive system:Intestine');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (347,'Excretory system',692,695,4,'root:Host-associated:Fish:Excretory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (348,'Kidneys',693,694,5,'root:Host-associated:Fish:Excretory system:Kidneys');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (349,'Reproductive system',696,697,4,'root:Host-associated:Fish:Reproductive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (350,'Skin',698,701,4,'root:Host-associated:Fish:Skin');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (351,'Slime',699,700,5,'root:Host-associated:Fish:Skin:Slime');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (352,'Fungi',703,704,3,'root:Host-associated:Fungi');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (353,'Human',705,816,3,'root:Host-associated:Human');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (354,'Circulatory system',706,709,4,'root:Host-associated:Human:Circulatory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (355,'Blood',707,708,5,'root:Host-associated:Human:Circulatory system:Blood');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (356,'Digestive system',710,747,4,'root:Host-associated:Human:Digestive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (357,'Hindgut',711,714,5,'root:Host-associated:Human:Digestive system:Hindgut');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (358,'Rectum',712,713,6,'root:Host-associated:Human:Digestive system:Hindgut:Rectum');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (359,'Intestine',715,716,5,'root:Host-associated:Human:Digestive system:Intestine');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (360,'Large intestine',717,722,5,'root:Host-associated:Human:Digestive system:Large intestine');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (361,'Fecal',718,719,6,'root:Host-associated:Human:Digestive system:Large intestine:Fecal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (362,'Sigmoid colon',720,721,6,'root:Host-associated:Human:Digestive system:Large intestine:Sigmoid colon');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (363,'Oral',723,746,5,'root:Host-associated:Human:Digestive system:Oral');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (364,'Attached Keratinized gingiva',724,725,6,'root:Host-associated:Human:Digestive system:Oral:Attached Keratinized gingiva');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (365,'buccal mucosa',726,727,6,'root:Host-associated:Human:Digestive system:Oral:buccal mucosa');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (366,'hard palate',728,729,6,'root:Host-associated:Human:Digestive system:Oral:hard palate');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (367,'Palatine tonsils',730,731,6,'root:Host-associated:Human:Digestive system:Oral:Palatine tonsils');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (368,'Periodontal pockets',732,733,6,'root:Host-associated:Human:Digestive system:Oral:Periodontal pockets');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (369,'Saliva',734,735,6,'root:Host-associated:Human:Digestive system:Oral:Saliva');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (370,'Subgingival plaque',736,737,6,'root:Host-associated:Human:Digestive system:Oral:Subgingival plaque');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (371,'Duplicate -subgingival plaque',738,739,6,'Duplicate - root:Host-associated:Human:Digestive system:Oral:subgingival plaque');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (372,'Supragingival plaque',740,741,6,'root:Host-associated:Human:Digestive system:Oral:Supragingival plaque');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (373,'Throat',742,743,6,'root:Host-associated:Human:Digestive system:Oral:Throat');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (374,'tongue dorsum',744,745,6,'root:Host-associated:Human:Digestive system:Oral:tongue dorsum');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (375,'Excretory system',748,753,4,'root:Host-associated:Human:Excretory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (376,'Urethra',749,752,5,'root:Host-associated:Human:Excretory system:Urethra');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (377,'Urine',750,751,6,'root:Host-associated:Human:Excretory system:Urethra:Urine');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (378,'Fossil',754,757,4,'root:Host-associated:Human:Fossil');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (379,'Bone',755,756,5,'root:Host-associated:Human:Fossil:Bone');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (380,'Lympathic system',758,761,4,'root:Host-associated:Human:Lympathic system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (381,'Lymph nodes',759,760,5,'root:Host-associated:Human:Lympathic system:Lymph nodes');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (382,'Milk',762,763,4,'root:Host-associated:Human:Milk');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (383,'Nervous system',764,767,4,'root:Host-associated:Human:Nervous system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (384,'Cerebrospinal fluid',765,766,5,'root:Host-associated:Human:Nervous system:Cerebrospinal fluid');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (385,'Reproductive system',768,779,4,'root:Host-associated:Human:Reproductive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (386,'Female',769,770,5,'root:Host-associated:Human:Reproductive system:Female');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (387,'Vagina',771,778,5,'root:Host-associated:Human:Reproductive system:Vagina');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (388,'Introitus',772,773,6,'root:Host-associated:Human:Reproductive system:Vagina:Introitus');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (389,'Midpoint vagina',774,775,6,'root:Host-associated:Human:Reproductive system:Vagina:Midpoint vagina');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (390,'posterior fornix',776,777,6,'root:Host-associated:Human:Reproductive system:Vagina:posterior fornix');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (391,'Respiratory system',780,799,4,'root:Host-associated:Human:Respiratory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (392,'Nasopharyngeal',781,788,5,'root:Host-associated:Human:Respiratory system:Nasopharyngeal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (393,'anterior nares',782,783,6,'root:Host-associated:Human:Respiratory system:Nasopharyngeal:anterior nares');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (394,'Nasal cavity',784,785,6,'root:Host-associated:Human:Respiratory system:Nasopharyngeal:Nasal cavity');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (395,'Pharynx',786,787,6,'root:Host-associated:Human:Respiratory system:Nasopharyngeal:Pharynx');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (396,'Pulmonary system',789,798,5,'root:Host-associated:Human:Respiratory system:Pulmonary system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (397,'Lung',790,791,6,'root:Host-associated:Human:Respiratory system:Pulmonary system:Lung');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (398,'Sputum',792,793,6,'root:Host-associated:Human:Respiratory system:Pulmonary system:Sputum');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (399,'Trachea',794,795,6,'root:Host-associated:Human:Respiratory system:Pulmonary system:Trachea');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (400,'Viriome',796,797,6,'root:Host-associated:Human:Respiratory system:Pulmonary system:Viriome');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (401,'Skin',800,815,4,'root:Host-associated:Human:Skin');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (402,'Axilla',801,802,5,'root:Host-associated:Human:Skin:Axilla');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (403,'Medial distal leg',803,806,5,'root:Host-associated:Human:Skin:Medial distal leg');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (404,'Venous leg ulcers',804,805,6,'root:Host-associated:Human:Skin:Medial distal leg:Venous leg ulcers');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (405,'Naris',807,808,5,'root:Host-associated:Human:Skin:Naris');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (406,'retroauricular crease',809,810,5,'root:Host-associated:Human:Skin:retroauricular crease');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (407,'Umbilicus',811,812,5,'root:Host-associated:Human:Skin:Umbilicus');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (408,'Volar forearm',813,814,5,'root:Host-associated:Human:Skin:Volar forearm');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (409,'Insecta',817,820,3,'root:Host-associated:Insecta');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (410,'Digestive system',818,819,4,'root:Host-associated:Insecta:Digestive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (411,'Invertebrates',821,834,3,'root:Host-associated:Invertebrates');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (412,'Bryozoans',822,825,4,'root:Host-associated:Invertebrates:Bryozoans');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (413,'Gymnolaemates',823,824,5,'root:Host-associated:Invertebrates:Bryozoans:Gymnolaemates');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (414,'Cnidaria',826,829,4,'root:Host-associated:Invertebrates:Cnidaria');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (415,'Coral',827,828,5,'root:Host-associated:Invertebrates:Cnidaria:Coral');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (416,'Echinodermata',830,833,4,'root:Host-associated:Invertebrates:Echinodermata');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (417,'Sea Urchin',831,832,5,'root:Host-associated:Invertebrates:Echinodermata:Sea Urchin');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (418,'Mammals',835,902,3,'root:Host-associated:Mammals');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (419,'Circulatory system',836,839,4,'root:Host-associated:Mammals:Circulatory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (420,'Blood',837,838,5,'root:Host-associated:Mammals:Circulatory system:Blood');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (421,'Digestive system',840,867,4,'root:Host-associated:Mammals:Digestive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (422,'Fecal',841,844,5,'root:Host-associated:Mammals:Digestive system:Fecal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (423,'Uncharacterized',842,843,6,'root:Host-associated:Mammals:Digestive system:Fecal:Uncharacterized');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (424,'Foregut',845,848,5,'root:Host-associated:Mammals:Digestive system:Foregut');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (425,'Rumen',846,847,6,'root:Host-associated:Mammals:Digestive system:Foregut:Rumen');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (426,'Large intestine',849,854,5,'root:Host-associated:Mammals:Digestive system:Large intestine');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (427,'Cecum',850,851,6,'root:Host-associated:Mammals:Digestive system:Large intestine:Cecum');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (428,'Fecal',852,853,6,'root:Host-associated:Mammals:Digestive system:Large intestine:Fecal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (429,'Midgut',855,856,5,'root:Host-associated:Mammals:Digestive system:Midgut');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (430,'Oral cavity',857,860,5,'root:Host-associated:Mammals:Digestive system:Oral cavity');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (431,'Buccal mucosa',858,859,6,'root:Host-associated:Mammals:Digestive system:Oral cavity:Buccal mucosa');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (432,'Stomach',861,866,5,'root:Host-associated:Mammals:Digestive system:Stomach');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (433,'Endoperitrophic space',862,863,6,'root:Host-associated:Mammals:Digestive system:Stomach:Endoperitrophic space');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (434,'Rumen',864,865,6,'root:Host-associated:Mammals:Digestive system:Stomach:Rumen');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (435,'Excretory system',868,871,4,'root:Host-associated:Mammals:Excretory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (436,'Urine',869,870,5,'root:Host-associated:Mammals:Excretory system:Urine');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (437,'Gastrointestinal tract',872,877,4,'root:Host-associated:Mammals:Gastrointestinal tract');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (438,'Intestine',873,876,5,'root:Host-associated:Mammals:Gastrointestinal tract:Intestine');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (439,'Fecal',874,875,6,'root:Host-associated:Mammals:Gastrointestinal tract:Intestine:Fecal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (440,'Lymphatic',878,881,4,'root:Host-associated:Mammals:Lymphatic');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (441,'Lymph nodes',879,880,5,'root:Host-associated:Mammals:Lymphatic:Lymph nodes');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (442,'Milk',882,883,4,'root:Host-associated:Mammals:Milk');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (443,'Nervous system',884,887,4,'root:Host-associated:Mammals:Nervous system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (444,'Brain',885,886,5,'root:Host-associated:Mammals:Nervous system:Brain');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (445,'Reproductive system',888,889,4,'root:Host-associated:Mammals:Reproductive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (446,'Respiratory system',890,899,4,'root:Host-associated:Mammals:Respiratory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (447,'Nasopharyngeal',891,894,5,'root:Host-associated:Mammals:Respiratory system:Nasopharyngeal');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (448,'Nasal cavity',892,893,6,'root:Host-associated:Mammals:Respiratory system:Nasopharyngeal:Nasal cavity');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (449,'Pulmonary system',895,898,5,'root:Host-associated:Mammals:Respiratory system:Pulmonary system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (450,'Viriome',896,897,6,'root:Host-associated:Mammals:Respiratory system:Pulmonary system:Viriome');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (451,'Skin',900,901,4,'root:Host-associated:Mammals:Skin');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (452,'Microbial',903,910,3,'root:Host-associated:Microbial');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (453,'Bacteria',904,905,4,'root:Host-associated:Microbial:Bacteria');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (454,'Dinoflagellates',906,909,4,'root:Host-associated:Microbial:Dinoflagellates');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (455,'Endosymbionts',907,908,5,'root:Host-associated:Microbial:Dinoflagellates:Endosymbionts');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (456,'Mollusca',911,930,3,'root:Host-associated:Mollusca');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (457,'Digestive system',912,919,4,'root:Host-associated:Mollusca:Digestive system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (458,'Ceca',913,916,5,'root:Host-associated:Mollusca:Digestive system:Ceca');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (459,'Uncharacterized',914,915,6,'root:Host-associated:Mollusca:Digestive system:Ceca:Uncharacterized');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (460,'Glands',917,918,5,'root:Host-associated:Mollusca:Digestive system:Glands');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (461,'Respiratory system',920,927,4,'root:Host-associated:Mollusca:Respiratory system');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (462,'Gills',921,926,5,'root:Host-associated:Mollusca:Respiratory system:Gills');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (463,'Extracellular',922,923,6,'root:Host-associated:Mollusca:Respiratory system:Gills:Extracellular');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (464,'Intracellular',924,925,6,'root:Host-associated:Mollusca:Respiratory system:Gills:Intracellular');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (465,'Shell',928,929,4,'root:Host-associated:Mollusca:Shell');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (466,'Plants',931,960,3,'root:Host-associated:Plants');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (467,'Phylloplane',932,937,4,'root:Host-associated:Plants:Phylloplane');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (468,'Endophytes',933,934,5,'root:Host-associated:Plants:Phylloplane:Endophytes');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (469,'Epiphytes',935,936,5,'root:Host-associated:Plants:Phylloplane:Epiphytes');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (470,'Rhizome',938,941,4,'root:Host-associated:Plants:Rhizome');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (471,'Epiphytes',939,940,5,'root:Host-associated:Plants:Rhizome:Epiphytes');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (472,'Rhizoplane',942,949,4,'root:Host-associated:Plants:Rhizoplane');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (473,'Endophytes',943,944,5,'root:Host-associated:Plants:Rhizoplane:Endophytes');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (474,'Epiphytes',945,946,5,'root:Host-associated:Plants:Rhizoplane:Epiphytes');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (475,'Soil',947,948,5,'root:Host-associated:Plants:Rhizoplane:Soil');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (476,'Rhizosphere',950,957,4,'root:Host-associated:Plants:Rhizosphere');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (477,'Epiphytes',951,952,5,'root:Host-associated:Plants:Rhizosphere:Epiphytes');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (478,'Soil',953,954,5,'root:Host-associated:Plants:Rhizosphere:Soil');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (479,'Forest soil',955,956,5,'root:Host-associated:Plants:Rhizosphere:Forest soil');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (480,'Root',958,959,4,'root:Host-associated:Plants:Root');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (481,'Porifera',961,962,3,'root:Host-associated:Porifera');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (482,'Protists',963,964,3,'root:Host-associated:Protists');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (483,'Protozoa',965,966,3,'root:Host-associated:Protozoa');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (484,'Reptile',967,974,3,'root:Host-associated:Reptile');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (485,'Oral cavity',968,973,4,'root:Host-associated:Reptile:Oral cavity');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (486,'Venom gland',969,972,5,'root:Host-associated:Reptile:Oral cavity:Venom gland');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (487,'Venom',970,971,6,'root:Host-associated:Reptile:Oral cavity:Venom gland:Venom');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (488,'Spiralia',975,976,3,'root:Host-associated:Spiralia');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (489,'Tunicates',977,980,3,'root:Host-associated:Tunicates');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (490,'Ascidians',978,979,4,'root:Host-associated:Tunicates:Ascidians');
INSERT INTO BIOME_HIERARCHY_TREE (biome_id,biome_name,lft,rgt,depth,lineage) VALUES (491,'Control',982,983,2,'root:Control');