# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emg_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisjob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='analysisstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='biomehierarchytree',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='experimenttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pipelinerelease',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pipelinereleasetool',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pipelinetool',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={},
        ),
        migrations.AlterModelOptions(
            name='samplepublication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studypublication',
            options={},
        ),
    ]
