# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emg_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('BiomeHierarchyTree', 'Biome'),

        migrations.RenameModel('PipelineRelease', 'Pipeline'),

        migrations.RenameModel('AnalysisJob', 'Run'),
        migrations.AlterField(
            model_name='run',
            name='external_run_ids',
            field=models.CharField(
                db_column='EXTERNAL_RUN_IDS', max_length=100),
        ),
        migrations.RenameField(
            model_name='run',
            old_name='job_id',
            new_name='run_id',
        ),
        migrations.RenameField(
            model_name='run',
            old_name='external_run_ids',
            new_name='accession',
        ),
        migrations.RemoveField(
            model_name='run',
            name='re_run_count',
        ),

        migrations.RenameField(
            model_name='sample',
            old_name='ext_sample_id',
            new_name='accession',
        ),

        migrations.RenameField(
            model_name='study',
            old_name='ext_study_id',
            new_name='accession',
        ),
        migrations.RemoveField(
            model_name='study',
            name='experimental_factor',
        ),
        migrations.RemoveField(
            model_name='study',
            name='ncbi_project_id',
        ),

    ]
