# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emg_api', '0002_cleanup_and_rename'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gsccvcv',
            unique_together=set([('var_name', 'var_val_cv')]),
        ),
        migrations.AlterUniqueTogether(
            name='sampleann',
            unique_together=set([('sample', 'var')]),
        ),
        migrations.AlterUniqueTogether(
            name='variablenames',
            unique_together=set([('var_id', 'var_name')]),
        ),
    ]
