# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emg_api', '0002_auto_20170628_1440'),
    ]

    operations = [
        migrations.RenameModel('BiomeHierarchyTree', 'Biome'),
        migrations.RenameModel('PipelineRelease', 'Pipeline'),
        migrations.RenameModel('AnalysisJob', 'Run'),
        migrations.AlterModelOptions(
            name='analysisstatus',
            options={'ordering': ('analysis_status_id',)},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('pub_id',)},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('accession',)},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ('accession',)},
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='ext_sample_id',
            new_name='accession',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='ext_study_id',
            new_name='accession',
        ),
        migrations.AlterField(
            model_name='analysisstatus',
            name='analysis_status',
            field=models.CharField(blank=True, db_column='ANALYSIS_STATUS', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='experimenttype',
            name='experiment_type',
            field=models.CharField(blank=True, db_column='EXPERIMENT_TYPE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pipelinereleasetool',
            name='how_tool_used_desc',
            field=models.TextField(blank=True, db_column='HOW_TOOL_USED_DESC', null=True),
        ),
        migrations.AlterField(
            model_name='pipelinereleasetool',
            name='pipeline',
            field=models.ForeignKey(db_column='PIPELINE_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emg_api.Pipeline'),
        ),
        # migrations.AlterField(
        #     model_name='pipelinereleasetool',
        #     name='tool',
        #     field=models.ForeignKey(blank=True, db_column='TOOL_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='emg_api.PipelineTool'),
        # ),
        migrations.AlterField(
            model_name='pipelinereleasetool',
            name='tool_group_id',
            field=models.DecimalField(blank=True, db_column='TOOL_GROUP_ID', decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pipelinetool',
            name='description',
            field=models.TextField(blank=True, db_column='DESCRIPTION', null=True),
        ),
        migrations.AlterField(
            model_name='pipelinetool',
            name='exe_command',
            field=models.CharField(blank=True, db_column='EXE_COMMAND', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pipelinetool',
            name='tool_name',
            field=models.CharField(blank=True, db_column='TOOL_NAME', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pipelinetool',
            name='version',
            field=models.CharField(blank=True, db_column='VERSION', max_length=30, null=True),
        ),
        # migrations.AlterField(
        #     model_name='sample',
        #     name='biome',
        #     field=models.ForeignKey(blank=True, db_column='BIOME_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='emg_api.Biome'),
        # ),
        # migrations.AlterField(
        #     model_name='sample',
        #     name='study',
        #     field=models.ForeignKey(blank=True, db_column='STUDY_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='emg_api.Study'),
        # ),
        # migrations.AlterField(
        #     model_name='samplepublication',
        #     name='pub',
        #     field=models.ForeignKey(blank=True, db_column='PUB_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='emg_api.Publication'),
        # ),
        # migrations.AlterField(
        #     model_name='samplepublication',
        #     name='sample',
        #     field=models.ForeignKey(db_column='SAMPLE_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emg_api.Sample'),
        # ),
        # migrations.AlterField(
        #     model_name='study',
        #     name='biome',
        #     field=models.ForeignKey(blank=True, db_column='BIOME_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='emg_api.Biome'),
        # ),
        migrations.AlterField(
            model_name='study',
            name='first_created',
            field=models.DateTimeField(blank=True, db_column='FIRST_CREATED', null=True),
        ),
        # migrations.AlterField(
        #     model_name='studypublication',
        #     name='pub',
        #     field=models.ForeignKey(blank=True, db_column='PUB_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='emg_api.Publication'),
        # ),
        migrations.AlterField(
            model_name='studypublication',
            name='study',
            field=models.ForeignKey(db_column='STUDY_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emg_api.Study'),
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together=set([('sample_id', 'accession')]),
        ),
        migrations.AlterUniqueTogether(
            name='samplepublication',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='study',
            name='experimental_factor',
        ),
        migrations.RemoveField(
            model_name='study',
            name='ncbi_project_id',
        ),
        migrations.AlterUniqueTogether(
            name='study',
            unique_together=set([('study_id', 'accession')]),
        ),
        migrations.AlterUniqueTogether(
            name='studypublication',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together=set([('pipeline_id', 'release_version')]),
        ),
    ]

