name: Testing

on: [push, pull_request]
env:
  EMG_CONFIG: ${{ github.workspace }}/ci/configuration.yaml

jobs:
  build:

    runs-on: ubuntu-latest
    services:
        mysql:
            image: mysql:5.7
            env:
                MYSQL_ALLOW_EMPTY_PASSWORD: yes
                MYSQL_DATABASE: emg
            ports:
                - '3306:3306'
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: 🐍 - Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: 💾 Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.0
    - name: ⚙️ - Checking environment
      run: |
        python -V
        mysql --version
    - name: 🔧 - Install Dependencies
      run: |
        pip install -U git+git://github.com/EBI-Metagenomics/emg-backlog-schema.git
        pip install -U git+git://github.com/EBI-Metagenomics/ena-api-handler.git
        pip install -U -r requirements-test.txt
        pip install "flake8==3.4" "pycodestyle==2.3.1" pep8-naming
        pip install "git+git://github.com/EBI-Metagenomics/django-rest-framework-json-api@develop#egg=djangorestframework-jsonapi"
        python setup.py sdist
        pip install -U .
        pip freeze
    - name: 🧪 - Testing
      run: |
        cat $EMG_CONFIG
        python setup.py test
    - name: Flake
      run: |
        flake8 --version
        flake8 -v .
#    - name: 📮 - Slack Notification
#      uses: rtCamp/action-slack-notify@v2
#      continue-on-error: true
#      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
#      env:
#        SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
#        SLACK_USERNAME: "Github Actions API"
#        SLACK_ICON_EMOJI: ":octocat:"
#        SLACK_TITLE: "CI API results in GitHub Actions"
#        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#        SLACK_CHANNEL: "#interpro7"
#        MSG_MINIMAL: Actions URL
